### PR TITLE
Region import failures

### PR DESCRIPTION
**Pull request by pford**
Issues #334 and #343 

- Importing regions with no direction coordinate causes an exception (even for pixel imports, for now).  The image's coordinate system is checked and a warning issued, and the region import fails.
- When a region's syntax or definition fails, the import fails for CRTF region files but succeeds for DS9 region files if any regions are successfully imported; warnings are issued for the failed regions.
- If the region file does not exist, the import fails.

### CODE REVIEW

**Comment by markccchiang** [comment]
@pford I am trying to understand the codes. So the remaining problem is that when a region's syntax or definition fails, such a file can not be imported if it is a CRTF region, but can be imported if it is a DS9 region?

**Comment by pford** [comment]
@markccchiang that is correct.  For a CRTF import, IMPORT_REGION_ACK should set success=False with a message indicating the error.  For a DS9 import, IMPORT_REGION_ACK should set success=True, import the good regions, and set a message indicating the error as well as a log message (ERROR_DATA) with a warning indicating the failed region(s).  If the DS9 import should also entirely fail, @kswang1029 please let me know.

**Comment by markccchiang** [comment]
According to @kswang1029, we should import good regions which have the right syntax or definitions. If there are bad regions with poor definitions, we should send a message indicating which ones are wrong. So for the importing of DS9 region file, there is no problem. But for the CRTF region file, maybe we have to modify the casacode class `RegionTextParser`, in order to fit this requirement?

**Comment by pford** [comment]
This PR is to get the DS9 region implementation code into dev (already in release/1.2 branch), then I will contact Dave about modifying casacode for a separate PR.

**Pull request merged**
