### PR TITLE
Modify the contour data message

### PR DESCRIPTION
**Pull request by markccchiang**
It is to fit the frontend requirement in the frontend [PR 1636](https://github.com/CARTAvis/carta-frontend/pull/1636). A new bool variable `is_long_task` is added to the contour data message. `is_long_task=true` if the estimated time of contour process is greater than 1 second. It decides whether to show the contour progress bar in the frontend.

### CODE REVIEW

**Comment by kswang1029** [comment]
@markccchiang @duidae @veggiesaurus is it possible to just show one progress bar?

https://user-images.githubusercontent.com/20819712/139231084-de2f552a-552f-4a71-be0b-37fba31d9d22.mov

**Comment by kswang1029** [comment]
@markccchiang @duidae @veggiesaurus 
animating a FITS cube may still trigger the blinking effect if we plot _more_ contours. I suggest when animating we don't show the progress bar at all if possible even if it takes some time to generate contours per channel. 


https://user-images.githubusercontent.com/20819712/139232206-49e64fad-27ad-4d8a-b3b1-f50955f426b8.mov

**Comment by markccchiang** [comment]
> @markccchiang @duidae @veggiesaurus is it possible to just show one progress bar?

Different contour levels run in parallel in the backend. To unify progress bars, I think we can show the minimum progress value of all contour levels on each update.

**Review by confluence — APPROVED** [review]

**Comment by veggiesaurus** [comment]
moved to draft while we determine if backend changes are actually required

**Pull request closed without merging**
