### PR TITLE
1063 fix info/load time for FITS with long history

### LINKED ISSUE #1063: Loading FITS Images from NED Hangs CARTA
Using CARTA v1.4 server find that trying to load a FITS image from NED, specifically the FITS image at http://ned.ipac.caltech.edu/uri/NED::Image/fits/2009A+A...506.1123H/NGC_0253:I:vla+eff_6_cm_I_30arcs:H2009, hangs CARTA.  Never completes loading image, with spinning arrow display trying to show file information.

### PR DESCRIPTION
**Pull request by pford**
Closes #1063 

Find number of headers using cfitsio; if > 10,000 use CartaFitsImage which will read all headers into one list `_all_header_strings` and non-HISTORY headers into another list `_image_header_strings`.  Using the image headers list to set up CartaFitsImage (particularly the coordinate system) speeds this up considerably.  This has no effect for an image with a large number of headers which are not HISTORY.  All headers, including history, are shown in the file browser.

NOTE the image does not use beam information in the HISTORY headers - see #935 and #1083 (same as previous behavior, which removes the history beam when casacore::FITSImage is used).

### CODE REVIEW

**Review by kswang1029 — COMMENTED** [review]
@pford yes this improves the file info generation time very significantly. I tried the case with ~<10000 header entries (9900 HISTORY entries) and it took a while to get the file info generated. I wonder if we should set the threshold from 10000 to 2000 or 5000 for example. I tested those two cases and the elapsed time was reasonable in my point of view. What would be drawback if we set a lower threshold?

**Comment by veggiesaurus** [comment]
> @pford yes this improves the file info generation time very significantly. I tried the case with ~<10000 header entries (9900 HISTORY entries) and it took a while to get the file info generated. I wonder if we should set the threshold from 10000 to 2000 or 5000 for example. I tested those two cases and the elapsed time was reasonable in my point of view. What would be drawback if we set a lower threshold?

The only additional performance issue I think this would introduce is actually counting the number of headers, but that's probably not too bad. cfitsio does this by reading 80 characters at a time IIRC

**Review by confluence — APPROVED** [review]

**Review by markccchiang — APPROVED** [review]

**Comment by pford** [comment]
> > @pford yes this improves the file info generation time very significantly. I tried the case with ~<10000 header entries (9900 HISTORY entries) and it took a while to get the file info generated. I wonder if we should set the threshold from 10000 to 2000 or 5000 for example. I tested those two cases and the elapsed time was reasonable in my point of view. What would be drawback if we set a lower threshold?
> 
> The only additional performance issue I think this would introduce is actually counting the number of headers, but that's probably not too bad. cfitsio does this by reading 80 characters at a time IIRC

The drawback to using a threshold is that users would have to use another tool besides CARTA to get the full history of what processing has been done to obtain the image.  I do not know how important this is to users, so it is a user/science team decision on feature vs performance.  I think if we truncate the history we would need to let users know that it is incomplete.

The headers are already counted in this PR using cfitsio `fits_get_hdrspace` to force using CartaFitsImage over casacore::FITSImage when the number of headers is high.

**Comment by kswang1029** [comment]
> > > @pford yes this improves the file info generation time very significantly. I tried the case with ~<10000 header entries (9900 HISTORY entries) and it took a while to get the file info generated. I wonder if we should set the threshold from 10000 to 2000 or 5000 for example. I tested those two cases and the elapsed time was reasonable in my point of view. What would be drawback if we set a lower threshold?
> > 
> > 
> > The only additional performance issue I think this would introduce is actually counting the number of headers, but that's probably not too bad. cfitsio does this by reading 80 characters at a time IIRC
> 
> The drawback to using a threshold is that users would have to use another tool besides CARTA to get the full history of what processing has been done to obtain the image. I do not know how important this is to users, so it is a user/science team decision on feature vs performance. I think if we truncate the history we would need to let users know that it is incomplete.
> 
> The headers are already counted in this PR using cfitsio `fits_get_hdrspace` to force using CartaFitsImage over casacore::FITSImage when the number of headers is high.

I am confused. With an image having 20000 HISTORY, I can still see all history entries in the file info. 🤔 Test images are attached.
[set_fits_long_history.zip](https://github.com/CARTAvis/carta-backend/files/8953965/set_fits_long_history.zip)

**Comment by pford** [comment]
> I am confused. With an image having 20000 HISTORY, I can still see all history entries in the file info. 🤔 Test images are attached. [set_fits_long_history.zip](https://github.com/CARTAvis/carta-backend/files/8953965/set_fits_long_history.zip)

All of the headers are saved to be shown in the file info, but only the non-history headers are used to set up the image CoordinateSystem.  This step was the biggest performance hit when all headers were used.

**Comment by kswang1029** [comment]
> > I am confused. With an image having 20000 HISTORY, I can still see all history entries in the file info. 🤔 Test images are attached. [set_fits_long_history.zip](https://github.com/CARTAvis/carta-backend/files/8953965/set_fits_long_history.zip)
> 
> All of the headers are saved to be shown in the file info, but only the non-history headers are used to set up the image CoordinateSystem. This step was the biggest performance hit when all headers were used.

I see. I think it is okay to just use non-HISTORY entries to set up image CoordinateSystem. Normally information in HISTORY should have zero contribution to build up coordinate system I suppose (except the aips beam patch in casacore(?))@veggiesaurus @pford @confluence would you agree?

**Comment by confluence** [comment]
@pford @kswang1029 I'm not sure if we're all on the same page -- my understanding is that KS is suggesting using a smaller threshold of total headers (smaller than 10K) to trigger the optimisation, not introducing a threshold for truncating the history headers in the viewer.

Is there any reason not to do this for *all* files? Is there a significant performance overhead for files with fewer headers?

**Comment by confluence** [comment]
@kswang1029 I made my last comment before seeing yours. I see no reason not to do this optimisation for all files, if there is no performance drawback and the history headers are not used to set up the CoordinateSystem.

**Comment by kswang1029** [comment]
> @pford @kswang1029 I'm not sure if we're all on the same page -- my understanding is that KS is suggesting using a smaller threshold of total headers (smaller than 10K) to trigger the optimisation, not introducing a threshold for truncating the history headers in the viewer.
> 
> Is there any reason not to do this for _all_ files? Is there a significant performance overhead for files with fewer headers?

@confluence i think what @pford mentioned is if we have a header with 100 normal entries and 10000 history entries, only the 100 normal entries are used to build up coordiantesystem. If it is a header with 100 normal entries and 9899 history entries, all 9999 entries are used to set up coordiantesystem which takes time to go through all one by one (and most of them are ineffective in that task).

**Comment by veggiesaurus** [comment]
> I see. I think it is okay to just use non-HISTORY entries to set up image CoordinateSystem. Normally information in HISTORY should have zero contribution to build up coordinate system I suppose 

We may get some push back from users, but I am fiercely against using `HISTORY` and `COMMENT` headers for anything other than plain text information for the users, so I agree

**Comment by pford** [comment]
> @pford @kswang1029 I'm not sure if we're all on the same page -- my understanding is that KS is suggesting using a smaller threshold of total headers (smaller than 10K) to trigger the optimisation, not introducing a threshold for truncating the history headers in the viewer.
> 
> Is there any reason not to do this for _all_ files? Is there a significant performance overhead for files with fewer headers?

@confluence thank you for the explanation, I misunderstood it as a threshold for the number of headers to read.

Since the loader and its image are used for extended file info as well as for image access after it is loaded, using this for all files would eliminate the use of casacore::FITSImage entirely (unless I add a flag to use CartaFitsImage for the file browser only).  The casacore version is the default since it has been tested and used more extensively.

**Review by kswang1029 — APPROVED** [review]
having 2000 as threshold is good and appears fast in my test env. Also tested fits.gz and it works properly.

**Pull request merged**
