### PR TITLE
Fix ellipse rotation handling

### LINKED ISSUE #495: swapped major/minor axes of ellipse when exporting as region file
Not sure if this is frontend of backend.

reported by user 

> When I export an ellipse region using the IDIA server version of CARTA, using the default options of CTRF format, and world coordinates, and then import it again, it's rotated by 90 degrees, even when imported onto the same image. The same occurs when using ds9 region format, but doesn't seem to occur for either format when using pixel coordinates. None of the other region shapes seem to have this issue, at least for CTRF format and world coordinates.

https://github.com/CARTAvis/carta/issues/18

### PR DESCRIPTION
**Pull request by pford**
* Adjust control points, rotation for WCEllipsoid but store original values in world coordinates for export
* On import, check if AnnEllipse bmaj, bmin, rotation changed from file params

Closes #495 .

### CODE REVIEW

**Comment by pford** [comment]
@kswang1029 please check this for release patch.

**Comment by kswang1029** [comment]
@pford I tried to export a region (region 1 in the screenshot) and import back (region 2). Now region in world coordinate works fine. For region in image coordinate, it rendered correctly but in the region list, the displayed size seems crazy (dev branch displays fine).
Screen Shot 2020-04-20 at 1 43 17 PM

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@pford I tried to export a region (region 1 in the screenshot) and import back (as region 2). Now region in world coordinate works fine. For region in image coordinate, the displayed size seems crazy (dev branch displays fine).
Screen Shot 2020-04-20 at 1 43 17 PM

**Comment by pford** [comment]
@kswang1029 please retest with latest commit

**Comment by kswang1029** [comment]
@pford Looking good now! 👍

**Pull request merged**
