### PR TITLE
skip running casa_data_autoupdate if checking version

### PR DESCRIPTION
**Pull request by ajm-ska**
**Description**

At the moment if a user just wants to check the version number with `--version` or `-v`, the `/usr/bin/carta` script runs the `casa_data_autoupdate` script. This is not really necessary.
```
[ajm@almat1 ~]# carta --version
CARTA will use the default ephemerides and geodetic data.
4.0.0-rc.0
```
Similarly, it is not necessary to run for `--help` or `-h`

We could easily skip it with the following modification to `/usr/bin/carta`:
```
if [[ ! "$@" =~ (--version|-v|--help|-h) ]]; then
    if [ -x "$(command -v casa_data_autoupdate)" ]; then
        casa_data_autoupdate
    fi
fi
```

This is a very small PR, so maybe we don't really need an accompanying issue?

**Checklist**

- [x] no changelog update needed
- [x] e2e test passing / corresponding fix added / new e2e test created
- [x] no protobuf update needed
- [x] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Comment by confluence** [comment]
I think that we need to use real option parsing for this (using string parsing for this is fragile, and it's hard to avoid false positives and negatives). That makes this non-trivial enough that I think we should delay it to the next release.

**Review by confluence — APPROVED** [review]
I initially thought that the current solution (after adding whitespace) introduces false negatives if the argument is at the start or end of the string, but I see that adding whitespace around the whole string in the check prevents that. I can't reproduce any false positives or negatives, and I think that this can be merged as-is.

**Comment by kswang1029** [comment]
@ajm-asiaa would you sync up this branch with dev please (15 commits behind)?

**Comment by kswang1029** [comment]
from @confluence 

> I think a complete test would be: 1) check that each of those options prevents the update from running; 2) check that --host and --verbosity don't; 3) check that putting the options first or last still works. Those were the problems we found before.

**Comment by kswang1029** [comment]
Using the backend executable from my dev environment, I tried

> ./carta_backend --frontend_folder /Users/kswang/carta_build/carta-frontend/build --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5 --version
> 
> ./carta_backend --version --frontend_folder /Users/kswang/carta_build/carta-frontend/build --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5
> 
> ./carta_backend --help --frontend_folder /Users/kswang/carta_build/carta-frontend/build --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5
> 
> ./carta_backend --frontend_folder /Users/kswang/carta_build/carta-frontend/build --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5 --help
> 
> ./carta_backend --frontend_folder /Users/kswang/carta_build/carta-frontend/build --version --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5
> 
> ./carta_backend --frontend_folder /Users/kswang/carta_build/carta-frontend/build --help --port 3002 --omp_threads 8 --debug_no_auth --no_browser --verbosity 5

and they all work fine.

Then I tried the macOS electron app with an alias pointed to `/Applications/CARTA-17b983ea-f35e050e-2023-12-11.app/Contents/MacOS/CARTA-17b983ea-f35e050e-2023-12-11`. The electron window will be launched instead of showing a version string in the terminal with I set --version. With v4.0 I see

> carta --version
> CARTA will use the default ephemerides and geodetic data.
> 
> 4.0.0

Then I tried the AppImage (carta-17b983ea-f35e050e-2023-12-11-x86_64.AppImage) on ubuntu with --help and --version flags. I saw in both cases, "CARTA will use the default ephemerides and geodetic data" string showed up in the terminal.

So, @ajm-asiaa, do you think what I saw from the macOS electron app and AppImage was due to the extra configurations apart from the carta_backend executable?

**Comment by ajm-ska** [comment]
@kswang1029 For the macOS Electron app, the electron window launched instead of only showing the version string in the terminal because it would require this PR to be merged in the carta-package repository: https://github.com/CARTAvis/carta-package/pull/14

I'm not sure why the "CARTA will use the default ephemerides and geodetic data." line is also showing up there because it should be running the "carta-backend/bin/run.sh" script. So I should double-check Auto App Assembler is picking up the correct branches.

I forgot that the AppImage has its own slightly longer startup script:
https://github.com/CARTAvis/carta-package/blob/master/CARTA-AppImage-creator/AppRun
I'll make a branch and PR on the carta-package repo for the AppImage startup script with similar modifications.

**Comment by ajm-ska** [comment]
I created and merged carta-package [PR#15](https://github.com/CARTAvis/carta-package/pull/15) and also went ahead and merged [PR#14](https://github.com/CARTAvis/carta-package/pull/14). They are just minor changes. 
I will create a new AppImage and macOS Electron app, and check the issue with the macOS Electron app.

**Comment by ajm-ska** [comment]
@kswang1029 All done. I think the macOS Electron app and AppImage appear to handle the --version flag properly now.

macOS Electron:
https://carta.asiaa.sinica.edu.tw/downloads/CARTA-9a502ee9-f35e050e-2023-12-12-4.0.0-test-arm64.dmg
`alias carta=/Applications/CARTA-9a502ee9-f35e050e-2023-12-12.app/Contents/MacOS/CARTA-9a502ee9-f35e050e-2023-12-12`

Appimage:
https://carta.asiaa.sinica.edu.tw/downloads/carta-9a502ee9-f35e050e-2023-12-12-x86_64.AppImage

**Review by acdo2002 — APPROVED** [review]
I checked the MacOS electron and Ubuntu AppImage with
./carta-xxx -v, they all work fine.

For MacOS electron (MacOS 13 + M1)

> CARTA will use the default ephemerides and geodetic data.

Only showed in the old MacOS electron(v4 official release), it does not show in `theCARTA-9a502ee9-f35e050e-2023-12-12.app`

For Ubuntu 22.04:
v3, v4, and 4.0.0-rc.0 are only show the carta version info without anyephemerides and geodetic data info.

**Review by kswang1029 — APPROVED** [review]
looks good.

**Pull request merged**
