### PR TITLE
Unit tests for the file list and file info

### PR DESCRIPTION
**Pull request by markccchiang**
This is part of #797. Migrating the ICD tests of file list and file info to the backend unit tests. Thanks for @acdo2002 preparing sample image files.

### CODE REVIEW

**Review by confluence — CHANGES_REQUESTED** [review]
As we previously discussed, these should be lower-level unit tests which bypass the messaging interface and directly call functions on internal classes (in this case the classes in `src/FileList/`).

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
echoing what @confluence said: We don't just want an ICD test translated to the backend. Unit tests of the actual functionality are what we want.

I'd also like to have them in separate files i.e. `TestFileInfo.cc` and `TestFileList.cc`.

Do we really need the very long history entries in the test data?

**Comment by markccchiang** [comment]
> 
> Do we really need the very long history entries in the test data?

I think we don't need very long history entries in the test data. @acdo2002 could you please remove `HISTORY` entries in sample images `M17_SWex_unit.image` and `M17_SWex_unit.fits`?

**Comment by acdo2002** [comment]
@markccchiang I have put the update unit tests image in [here](https://drive.google.com/drive/folders/1Wi1WxXk6gg-aQQXhXTTEN8m8vM4bWMcX?usp=sharing), please  download "unit-test.zip".

I have remove the HISTORY related header in fits.
However casa format is converted from fits via CASA, there will generate few HISTORY header. But the new version is still smaller than previous one.
I also update the hdf5 & miriad format.

Now the exact image size:
(1)"M17_SWex.image" in files
type == 1
size = 112308
HDU_List = [""]

(2)"M17_SWex.fits" in files
type == 0
size = 8640
HDU_List = [""]

(3)"M17_SWex.miriad" in files
type == 3
size = 3040
HDU_List = [""]

(4)"M17_SWex.hdf5" in files
type == 2
size = 25040
HDU_List = ["0"]

**Comment by markccchiang** [comment]
As for the file list test, it tests the `FileListHandler` class with sample files and folders. And I added a condition check that prevents users access the folder beyond the top-level folder via the `../` command. For the file info test, it tests classes `FileInfoLoader`, `FileExtInfoLoader` and the `FillExtendedFileInfo` function from `Session` with different file formats. The time spends on different classes with respect to file formats can also be seen from tests. The Casa file spends almost twice the time on getting file extended info than the other file formats.

**Review by confluence — APPROVED** [review]

**Pull request merged**
