### PR TITLE
removes deprecated auth support

### PR DESCRIPTION
**Pull request by veggiesaurus**
this PR removes all deprecated auth support in preparation for the carta-node-server implementation rolling out with 1.4. The following has been removed:

- API key and permissions checking
- Auth token and JSON file reading
- mongo support, as well as user/layout getters and setters

This should make building the backend simpler, as mongo and json-cpp are no longer required

### CODE REVIEW

**Review by confluence — CHANGES_REQUESTED** [review]
It looks like there's some weird whitespace in here, and the format check is failing.

**Comment by confluence** [comment]
> It looks like there's some weird whitespace in here, and the format check is failing.

I see you fixed that while I was typing. :)

**Review by confluence — APPROVED** [review]
Looks OK.

**Comment by veggiesaurus** [comment]
@confluence some additional changes (the auth feature we discussed in today's meeting). Please re-review

**Review by confluence — APPROVED** [review]
Looks OK.

**Pull request merged**
