### PR TITLE
Support annotation regions

### LINKED ISSUE #340: Support image annotation text file (backend)
Supported in v1.4:
- [x] name
- [x] color
- [x] line width
- [x] dashed line

Requirements for v4:
https://docs.google.com/document/d/1YCB_lIVH8ftJcNS0gliE2uHmuiowGkV6DQYJlfteJUM/edit#

Must support:

- [x] SetRegion
- [x] ExportRegion
- [x] ImportRegion
- [x] ResumeSession
- [x] Import/Export from matched image

### PR DESCRIPTION
**Pull request by pford**
Closes #340 to set annotation regions and import/export them.

* What is implemented or fixed? Mention the linked issue(s), if any.
Implements feature in #340 .

* How does this PR solve the issue? Give a brief summary.
Updates Region, RegionImportExport, CrtfImportExport and Ds9ImportExport to add support for the new annotation regions.  Uses RegionStyle.AnnotationStyle for import/export of region properties not included in region definition.
Reuses code to handle vector and ruler as line (two points), compass as ellipse (center point and lengths instead of bmaj/bmin), and text box as rectangle (center point and width/height).

* Are there any companion PRs (frontend, protobuf)?
frontend [#2019](https://github.com/CARTAvis/carta-frontend/pull/2019), protobuf [#80](https://github.com/CARTAvis/carta-protobuf/pull/80)

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Create annotation regions in frontend, export in CRTF/DS9 pixel/world coordinates, import from file.

**Checklist**

- [x] changelog updated / ~~no changelog update needed~~
- [ ] e2e test passing / added corresponding fix
- [x] protobuf updated to the latest dev commit / ~~no protobuf update needed~~
- [ ] added reviewers and assignee
- [x] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Comment by pford** [comment]
@kswang1029 the backend branch is ready to start testing with the frontend.  Avoid text region import until issue in Slack channel is resolved.

**Comment by kswang1029** [comment]
> @kswang1029 the backend branch is ready to start testing with the frontend. Avoid text region import until issue in Slack channel is resolved.

Will do

**Comment by kswang1029** [comment]
@pford could you investigate why the attached ds9 region file cannot be imported? It works fine with v3-stable. The error message from the backend log is

> Region import failed: Invalid DS9 region or syntax: ellipse


[tmp.zip](https://github.com/CARTAvis/carta-backend/files/10575982/tmp.zip)

**Comment by pford** [comment]
@kswang1029 fixed.  The refactored code was not handling _ellipse annulus_ and _box annulus_ regions correctly and threw an exception.  Now it just adds an import error to the log: "DS9 ellipse annulus region not supported".

**Comment by kswang1029** [comment]
feature testing looks good as far as I can tell. Please switch to formal PR. Code review may proceed.

**Review by kswang1029 — APPROVED** [review]
manual tests and enhanced e2e tests are looking good. 👍

**Review by confluence — APPROVED** [review]

**Pull request merged**
