### PR TITLE
Fix a bug in Min/Max calculation

### PR DESCRIPTION
**Pull request by markccchiang**
This is to solve issue #307.

### CODE REVIEW

**Comment by markccchiang** [comment]
If the first element comes in the loop and it is the largest value in an array, then it will be assigned to `t_min`, not `t_max`. That is why it has to be two `if`. To avoid using two `if` and using one `if else`, maybe we can initialize `t_min` and `t_max` values as the first element of the finite array.

**Comment by veggiesaurus** [comment]
> If the first element comes in the loop and it is the largest value in an array, then it will be assigned to `t_min`, not `t_max`. That is why it has to be two `if`. To avoid using two `if` and using one `if else`, maybe we can initialize `t_min` and `t_max` values as the first element of the finite array.

You can do that, although we will just need to ensure that we handle the case where the array is empty. Better to have some extra branching code in an _O(1)_ part of the function than in an _O(N)_ part.

**Comment by markccchiang** [comment]
After several trials, I think it is not a good idea to initialize `t_min` and `t_max` as the first element of the finite array. Since it is a parallel calculation, any step to identify the value is finite or NaN and then use it to initialize `t_min` and `t_max` would increase the complexity of this algorithm.

**Comment by veggiesaurus** [comment]
why not just use `-FLOAT_MAX` and `FLOAT_MAX`? (or rather, the c++11 equivalent)  and then in the `join` handle those situations where _t_min or _t_max are still those values.

**Comment by markccchiang** [comment]
> why not just use `-FLOAT_MAX` and `FLOAT_MAX`? (or rather, the c++11 equivalent) and then in the `join` handle those situations where _t_min or _t_max are still those values.

**Comment by markccchiang** [comment]
> > why not just use `-FLOAT_MAX` and `FLOAT_MAX`? (or rather, the c++11 equivalent) and then in the `join` handle those situations where _t_min or _t_max are still those values.

Sorry! I just accidentally close this PR. If my understanding is correct, `t_min` and `t_max` are already initialized as `std::numeric_limits<T>::max()` and `std::numeric_limits<T>::min()`.

**Comment by markccchiang** [comment]
Test the time spending for min/max calculation with large images like `LMCq.fits` or `h_m51_b_s05_drz_sci.fits`. I don't see there is a large difference between the original and newly changed code.

**Comment by kswang1029** [comment]
@markccchiang could you also try with images in set_Gaussian2D? ie 20k, 40k and 80k.

**Comment by markccchiang** [comment]
For 20k image, the average time spent is 2653(original) / 2541(new) ms. For 40k image, the average time spent is 10313(original) / 11794(new) ms.

**Comment by veggiesaurus** [comment]
Ok. I guess that's an acceptable change. I'll approve and merge

**Pull request merged**
