### PR TITLE
Added a default FITS image, mostly for use by the controller

### PR DESCRIPTION
**Pull request by confluence**
This is a default image for the Ubuntu package to install to a system data directory, and for the controller to use in its default unconfigured state.

### CODE REVIEW

**Comment by kswang1029** [comment]
Nice

default fits-image-2021-3-30-20-44-52

**Comment by veggiesaurus** [comment]
@confluence don't you need to edit the `CMakeLists.txt` to ensure this gets copied to `/usr/local/share/carta` when installing?

**Comment by confluence** [comment]
For the Ubuntu packages it would be `/usr/share/carta`. I was planning to leave this to the packages, like the icons. I'm not sure how easily we can find an appropriate data directory in the cmake config which will work with a source install on any platform.

**Comment by veggiesaurus** [comment]
> For the Ubuntu packages it would be `/usr/share/carta`. I was planning to leave this to the packages, like the icons. I'm not sure how easily we can find an appropriate data directory in the cmake config which will work with a source install on any platform.

Wouldn't it be `${CMAKE_INSTALL_PREFIX}/share/carta`?

**Comment by confluence** [comment]
Hmm, maybe that's fine. I guess this is simpler than icons. I will add it.

**Pull request merged**
