### PR TITLE
auth adjustments: fallback to query token

### PR DESCRIPTION
**Pull request by veggiesaurus**
Attempts to authenticate using URL query token if cookies or auth headers aren't available. This solves the issue of authenticating when the frontend and backend are hosted in separate locations.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@ajm-asiaa has requested this for the electron app and archive

**Review by confluence — APPROVED** [review]
Looks fine to me.

**Comment by veggiesaurus** [comment]
Will merge in once @ajm-asiaa has tested with his archive build

**Review by markccchiang — APPROVED** [review]

**Comment by ajm-ska** [comment]
@veggiesaurus I have tried it in my local ALMA-archive test implementation. It accepts the token and connects with the backend now.

However, I have noticed a new problem. It looks like the automatic file opening feature no longer works (i.e. adding &file=<image name> to the end of URL). It doesn't work with --debug_no_auth either, so it is probably related to some other change in the backend or frontend, or the way to use it has changed? 
Anyway, for now this Pull Request solves the token problem. 
I'll raise the automatic file opening issue on Slack.

**Pull request merged**
