### PR TITLE
Lock on the file list request handler

### PR DESCRIPTION
**Pull request by markccchiang**
This PR is for solving issue #17. Since the current lock is within Session, not cross Sessions. I extract the file list handler (`onFileListRequest`) from Session as an independent object, which handles all users' file list requests. Applying `tbb::mutex::scoped_lock` on file list handler so that it only process for one user a time. It could avoid the crash. There is no merge conflict with Pam's refactor PR.

### CODE REVIEW

**Comment by pford** [comment]
Please review the includes in FileListHandler.[cc, h].  Many are not needed.

**Comment by markccchiang** [comment]
Thanks for the comment! I have updated the branch including removed unused headers.

**Comment by pford** [comment]
Please fix centos6 and ubuntu failures in new FileListHandler code then will merge this.

**Comment by markccchiang** [comment]
Sorry for the late reply! I will fix it later today.

**Pull request merged**
