### PR TITLE
Set region states in the main thread

### PR DESCRIPTION
**Pull request by markccchiang**
It is to solve the stuck problem for region spectral profile calculations. By moving the setting of region states and its statistical requirements in the main thread. The region data streams or spectral profile calculations are done in TBB concurrent threads.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
this is going to be tricky to test, but @kswang1029 please try so. Once we're happy with it, we can also merge this into the release branch and deploy on IDIA's servers for some testing

**Comment by kswang1029** [comment]
I tested with three regions and requested their profiles in three different widgets. It looks good. Region can be created while profile is streaming. I also tried moving regions randomly while profile is steaming and it looks good too. If I switch to a new channel during profile streaming, it queues up and will update the image after profile streaming is done. 

As far as I can see so far, it is fine. 

will keep an eye on this in the coming days.

**Comment by veggiesaurus** [comment]
Ok then we can merge this once @robsimmonds and @pford have had a look at the PR

**Review by confluence — APPROVED** [review]
If this has been tested, I have no objections.

**Review by pford — APPROVED** [review]

**Pull request merged**
