### PR TITLE
ajm/unit tests to jenkinsfile

### PR DESCRIPTION
**Pull request by ajm-ska**
Don't merge just yet. I'm experimenting with the [JUnit plugin](https://plugins.jenkins.io/junit/#documentation) in Jenkins. 
Apparently the Unit Test information should appear in the `Checks` tab on the Github Pull request.
e.g.
https://github.com/timja-org/junit-attachments-test/pull/4/checks?check_run_id=1237630805
So let's see if it appears.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
@ajm-asiaa please mark as draft for now

**Comment by veggiesaurus** [comment]
I see the timer tests are failing, because the timer seems to be too inaccurate. I wonder if that's due to how we're running the tests, or whether I should just make the test more forgiving.

**Comment by ajm-ska** [comment]
@veggiesaurus It seemed the problem only one set of unit test results appearing in the "Tests" tab was that I had the `junit` reporting command inside the build steps. So if any of the tests failed, it was classed as a fail and skipped the `junit` command. So I have moved the junit test report command to be a post build step.

(I also fixed the segmentation fault problem of running `carta_backend_tests` on our Ubuntu server, and now I'm able to use method declaration style in order to keep the Jenkinsfile size below 64KB).

Now all the unit tests appear in the `Tests` tab. e.g https://carta.asiaa.sinica.edu.tw/blue/organizations/jenkins/carta-backend/detail/ajm%2Funit_tests_to_jenkinsfile/21/tests

Even though that seems to work, I see junit reports `No GitHub app credentials found` I'm currently trying to fix that by adding the "Github app" to Jenkins.

As you noted before, the Timer tests fail on MacOS. Shall we raise it as an issue on the backend repository, or should we just discuss it in Slack?

**Comment by veggiesaurus** [comment]
Let's raise an issue for it. Glad to see things are coming along. What was the Ubuntu segfault caused by?

**Comment by ajm-ska** [comment]
> What was the Ubuntu segfault caused by?

Before I figured out that I needed to do `-DCMAKE_CXX_STANDARD_LIBRARIES="-lgrpc++"` in the cmake command to fix the cmake build/linking problem, I had been trying to reinstall gRPC and Googletest from source and repositories to try and get around the problem.

I believe the segmentation fault at runtime was because it was using Googletest (v1.10.0) installed from source. 
It was picking up that version from here:
`-- Found GTest: /usr/local/lib/libgtest.a`
Although the test executable could build OK, it gave the segmentation fault.

After I removed those library files and did `apt-get install libgtest-dev`(1.8.1), it picked up that version from here:
`--Found GTest: /usr/lib/x86_64-linux-gnu/libgtest.a`
and then it could run without segmentation faults.

So I'm not sure the problem was related to the Googletest version, or the way I had installed it from source. Perhaps there was a conflict with library versions.

**Comment by ajm-ska** [comment]
@veggiesaurus I fixed the problem of Jenkins reporting the unit tests results back to Github, and it is finally working.

The problem was: 

> Recording test results
> [GitHub Checks] Causes for no suitable publisher found: 
> [GitHub Checks] Trying to resolve checks parameters from GitHub SCM...
> [GitHub Checks] No GitHub app credentials found: 'abe9061a-ed8f-485f-b13f-06f6cdbb8f44'

So I created and added a `GitHub app` to the CARTAvis repository and managed to add its credentials to Jenkins. The change caused Jenkins to process all existing branches again and it might have messed some things up. e.g. You may have noticed that some branches stuck with the yellow "pending" light on Github. Hopefully going forward, new branches will not have these issues. 

The good news is it seems to work:

> Recording test results
> [GitHub Checks] GitHub check (name: Tests / Unit Tests / CentOS7, status: COMPLETED) has been published.

On Github, on the Pull Request page, you can now see the results in the "Checks" tab:

Screenshot 2021-03-15 at 10 26 14

The failure indicated in `Jenkins` is a repeat of the failure in `Tests/ Unit Tests / MacOS`. So if the three "Tests" parts pass, then the overall "Jenkins" part would also pass.

**Comment by veggiesaurus** [comment]
@ajm-asiaa let me know if #775 solves the issues here :)

**Comment by ajm-ska** [comment]
@veggiesaurus Now that #775 solves the unit test Timer issue, I guess we can go ahead and merge the new Jenkinsfile (and .circleci/config.yml)

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
