### PR TITLE
Change the time zone in spdlog messages to UTC

### LINKED ISSUE #1151: inconsistent timestamps in the log file
**Describe the bug**
Myself and @kswang1029 have noticed that the timestamps in the log file are inconsistent. It is clear in the following example:
```
[2022-07-15 12:07:27.873] [CARTA] [info] Session 671617008 [127.0.0.1] Connected. Num sessions: 1
2022-07-15 04:07:40	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
[2022-07-15 12:07:43.281] [CARTA] [debug] Updated 1 preferences
```
It appears carta-casacore is writing in UTC time, but carta-backend is writing in local time, in this case UTC+08:00.

**To Reproduce**
1. Change your computer timezone to one that is not UTC time.
2. Use CARTA for a bit.
3. Check the log file.
4. Note that some time stamps in the log file use UTC time and others use UTC+timezone.

**Expected behavior**
All time stamps in the log file should be consistent. Perhaps local time (UTC+timezone) for personal desktop versions of CARTA?
(I'm not sure if UTC time would be preferred for carta-controller?)

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: Chrome
 - Browser version [e.g. 22]: 103
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**
It would be good if the format of the timestamps were consistent too.
Note the 2nd line does not use square brackets.
`[2022-07-15 12:07:27.873] [CARTA]`
`2022-07-15 04:07:40	INFO`	
Would this need to be a carta-casacore change?

### PR DESCRIPTION
**Pull request by markccchiang**
Closes #1151. Changing the time zone in spdlog messages from local to UTC.

### CODE REVIEW

**Review by confluence — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]

**Comment by kswang1029** [comment]
@pford thank you for studying the timestamp format in casacore. 👍

**Comment by markccchiang** [comment]
@kswang1029 Should we also apply this setting in the log file and performance log?

**Comment by kswang1029** [comment]
> 

yes everything displayed in the console and carta.log should be consistent in UTC.

**Comment by ajm-ska** [comment]
I was just about to ask about the log file. I thought I had checked out the wrong branch or that it wasn't working.

**Comment by kswang1029** [comment]
I see casacore log is missing in carta.log. It is seen on console. 🤔

**Comment by ajm-ska** [comment]
> I see casacore log is missing in carta.log. It is seen on console. 🤔

@kswang1029 I notice that too. Could it be that the casacore log was never written to `~/.carta/log/carta.log` when running a local version of CARTA, as I can't seem to find any casacore log entries from before?
I only see casacore log entries in the carta-controller log files in `/var/log/carta/`.

**Review by pford — APPROVED** [review]

**Review by ajm-ska — APPROVED** [review]

**Review by kswang1029 — APPROVED** [review]

**Pull request merged**
