### PR TITLE
Removed use of _waiting_task which was causing crash

### PR DESCRIPTION
**Pull request by robsimmonds**
Fixed some flow control logic.

### CODE REVIEW

**Comment by kswang1029** [comment]
tested with the mix page and the commit 1d61da9:

With supermosaic.10.fits at desired 15fps, at home with slower internet, the actual fps is smaller.
When I click stop, the animation does not stop immediately but keep showing some/several channels then jump back to the channel which I clicked stop. It feels like it is showing buffered channels until running out.
animator

**Comment by kswang1029** [comment]
another issue is when animation is ongoing, if I clicked "play" again, the channel will jump back to a certain former channel then keep going.
animator2

**Comment by veggiesaurus** [comment]
> tested with the mix page and the commit [1d61da9](https://github.com/CARTAvis/carta-backend/commit/1d61da90affa82982b83d58f23dae32ba34d26d7):
> 
> With supermosaic.10.fits at desired 15fps, at home with slower internet, the actual fps is smaller.
> When I click stop, the animation does not stop immediately but keep showing some/several channels then jump back to the channel which I clicked stop. It feels like it is showing buffer channels until running out.
> animator

I think this will be fixed with tiled rendering. We want it to stay on whichever channel you click stop on. At the moment there's no way for the front-end to know which channels are from an animation that has been stopped.

**Comment by veggiesaurus** [comment]
> another issue is when animation is ongoing, if I clicked "play" again, the channel will jump back to a certain former channel then keep going.

Front-end bug. I'll fix that

**Comment by robsimmonds** [comment]
@kswang1029 have discussed the too many frames issue with Angus. We understand this issue. It is due to the way we are calculating the flow control window not doing what we want on a slow network. There is a simple fix for it, but we will not apply that now since Angus is travelling. We can get that done later this week. It needs a more sophisticated fixed based on the sliding-window idea from TCP, but that will need more work and a lot of testing. So for now we have agreed to merge it into dev as is and accept that there is some strange behaviour when using very high frame rates with slow networks.

**Comment by kswang1029** [comment]
ok. please let me know if I can help on testing.

**Pull request merged**
