### PR TITLE
Fix the file info inconsistency for FITS

### LINKED ISSUE #916: file info inconsistency
The generated file info from FITS and CASA images has inconsistent entries, likely due to truncation error:

Screen Shot 2021-09-08 at 10 03 35 AM
Screen Shot 2021-09-08 at 10 03 22 AM

### PR DESCRIPTION
**Pull request by markccchiang**
Closes #916. Fix the file info inconsistency for FITS.

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
Yes, this fixes the issue as far as I can tell from my test images. 👍

**Comment by veggiesaurus** [comment]
I presume we now need to fix the file info ICD test?

**Review by veggiesaurus — APPROVED** [review]

**Review by confluence — APPROVED** [review]

**Comment by kswang1029** [comment]
> I presume we now need to fix the file info ICD test?

@acdo2002 could you check?

**Comment by acdo2002** [comment]
Yes, I am going to prepare a ICD update branch. 
Only update the snapshot for fits, also the hdf5 header too. 
but all these three type images will show the same Image reference coords with this backend branch.

**Comment by kswang1029** [comment]
> Yes, I am going to prepare a ICD update branch.
> Only update the snapshot for fits, also the hdf5 header too.
> but all these three type images will show the same Image reference coords with this backend branch.

Such inconsistency _should not_ ever exist in the ICD test actually. We should not apply an incorrect answer just to make the test pass. When did the ICD test get updated with this inconsistency? In my old robot test, reference world coordinates are identical and that’s why I spotted this problem.

**Comment by kswang1029** [comment]
> > Yes, I am going to prepare a ICD update branch.
> > Only update the snapshot for fits, also the hdf5 header too.
> > but all these three type images will show the same Image reference coords with this backend branch.
> 
> Such inconsistency _should not_ ever exist in the ICD test actually. We should not apply an incorrect answer just to make the test pass. When did the ICD test get updated with this inconsistency? In my old robot test, reference world coordinates are identical and that’s why I spotted this problem.

Do we ever test the computed entries? ie the context in the file info tab?

**Comment by acdo2002** [comment]
the last time I update is in Pam's branch.
Sorry I didn't notice the snapshot changes the Image reference coords.
I will be more careful about using snapshot.

**Pull request merged**
