### PR TITLE
ajm/c++17

### PR DESCRIPTION
**Pull request by ajm-ska**
The MacOS compiler seems to need CMAKE_CXX_STANDARD 17 set in the CMakeLists.txt file if the code is using C++17 functions.

### CODE REVIEW

**Comment by ajm-ska** [comment]
Or maybe I didn't think this out properly.... Now it failed to build on ubuntu:

```
CMake Error at CMakeLists.txt:125 (add_executable):

  CXX_STANDARD is set to invalid value '17'



CMake Error at carta-protobuf/CMakeLists.txt:11 (ADD_LIBRARY):

  CXX_STANDARD is set to invalid value '17'
```

**Comment by ajm-ska** [comment]
I have fixed the CI build issue. The problem was the cmake version in Ubuntu 16.04 was too old (3.5.1). It apparently needs at least cmake 3.8 to support the `CMAKE_CXX_STANDARD 17` line. I installed newer cmake from source in the Jenkins Ubuntu machine and the CircleCI Docker containers. Now it is working in all our CI systems.

**Comment by veggiesaurus** [comment]
@ajm-asiaa are you targeting the right branch here? I thought this would be a one-line fix? (not 667 lines)

**Comment by ajm-ska** [comment]
@veggiesaurus Oops! I'm sorry. I must have messed up with the branches! It is actually a one line fix. So I should have made my new branch from the 'dev' branch?

**Comment by veggiesaurus** [comment]
> @veggiesaurus Oops! I'm sorry. I must have messed up with the branches! It is actually a one line fix. So I should have made my new branch from the 'dev' branch?

Yes. Was yours from the release branch? perhaps just create a new PR for it?

**Comment by ajm-ska** [comment]
@veggiesaurus  OK. It seems I branched off `confluence/hdf5-mipmaps-no-get-multiple`. I have now branched from 'dev'. I'll try to delete this ajm/c++17 branch and pull request

**Comment by veggiesaurus** [comment]
> @veggiesaurus OK. It seems I branched off `confluence/hdf5-mipmaps-no-get-multiple`. I have now branched from 'dev'. I'll try to delete this ajm/c++17 branch and pull request

ok, great. @confluence can just merge the changes to `dev` into her branch instead

**Pull request closed without merging**
