### PR TITLE
Fix crash problem in moments ICD tests

### LINKED ISSUE #1070: carta_backend built with ASAN flags occasionally crashes running Moments ICD tests
**Describe the bug**
The carta-backend sometimes crashes when running the `MOMENTS_GENERATOR_FITS.test.ts` or `MOMENTS_GENERATOR_HDF5.test.ts` ICD tests. It can happen on Ubuntu 18.04, macOS12, and RHEL8. 
It is rare on Ubuntu 18.04, but occurs more frequently on macOS12 with the HDF5 test.

**To Reproduce**
Build carta-backend with the Address Sanitizer flags. 
Start the carta-backend.
Repeatedly run the `MOMENTS_GENERATOR_HDF5.test.ts` ICD test.
The carta-backend may crash on the 2nd or 3rd try.

**Expected behavior**
carta-backend should not crash.

**Screenshots or videos**
Here is the full crash log when running the `MOMENTS_GENERATOR_FITS.test.ts` test in the Ubuntu 18.04 Docker container [moment-generator-crash-ubuntu-1804.log](https://github.com/CARTAvis/carta-backend/files/8320635/moment-generator-crash-ubuntu-1804.log)
Here is the full crash log when running the `MOMENTS_GENERATOR_HDF5.test.ts` on the M1 macOS12 [moment-generator-crash-macos12.log](https://github.com/CARTAvis/carta-backend/files/8320922/moment-generator-crash-macos12.log)

**Platform info (please complete the following information):**
 - OS: Ubuntu 18.04 Docker container (ajmasiaa/bionic-jenkins-mar2022) and macOS12 

**Additional context**
I tried to trigger the issue through the frontend by manually following the steps in the ICD test, but can not create the crash event manually yet. 

This issue is probably related to other reported issues.

### PR DESCRIPTION
**Pull request by markccchiang**
Closes #1070. It seems the crash is not due to the moment images generation, but the destruction of Session which is called twice at the end of execution. The `DeleteSession` function is called twice and run in parallel under [SessionManager::OnDisconnect](https://github.com/CARTAvis/carta-backend/blob/dev/src/Session/SessionManager.cc#L109) and [~OnMessageTask()](https://github.com/CARTAvis/carta-backend/blob/dev/src/Session/OnMessageTask.h#L41). Now I add an unique lock for Sessions map's modification and check the existence of it before the deletion. @ajm-asiaa or @acdo2002 could you please check if the problem is solved if you have time? Thank you!

### CODE REVIEW

**Review by ajm-ska — APPROVED** [review]
This certainly appears to have fixed the problem! I ran the `MOMENTS_GENERATOR_HDF5` ICD test that was previously problematic and it consistently passes every time now.

@markccchiang Before this is merged into 'dev', would you be able to modify the `Jenkinsfile-full` to reinstate the ICD tests that we were previously skipping due to this issue? It is just a matter of deleting lines 947-950.

**Comment by acdo2002** [comment]
I found with the current backend, the ICD `MOMENTS_GENERATOR_FITS.test.ts` may passed (on Anthony's recent PR), however the carta_backend will crash on both Ubuntu and Mac (CASA and HDF5 are fine). 
However if I block the line 217, the ICD test will not crash the backend.

If I checkout to your branch, this strange behavior will be disappeared into Mac and Ubuntu.
The backend will alive even running `MOMENTS_GENERATOR_FITS.test.ts` many times.

**Comment by kswang1029** [comment]
does this branch include the fix https://github.com/CARTAvis/carta-backend/pull/1135? I see a regression from the "Import World Coordinate ds9 Region Made In ds9" e2e test and there are three regions missing which should have been fixed via https://github.com/CARTAvis/carta-backend/pull/1135.

**Comment by markccchiang** [comment]
> does this branch include the fix #1135? I see a regression from the "Import World Coordinate ds9 Region Made In ds9" e2e test and there are three regions missing which should have been fixed via #1135.

@kswang1029 Now I include the fix #1135. Please check it again. Thank you!

**Review by kswang1029 — APPROVED** [review]
no regression observed via e2e tests. Tried manual tests with a single backend having multiple sessions and kill the sessions one by one. No odd issue is observed. Session resume also works fine.

**Comment by robsimmonds** [comment]
This looks fine. This code is not called often in the live system which is why the issue has not been noticed before.

**Review by robsimmonds — APPROVED** [review]
Fine.

**Review by confluence — APPROVED** [review]

**Pull request merged**
