### PR TITLE
Fix unintentional insertion of null pointers into the sessions map

### LINKED ISSUE #1248: [carta python] backend crash due to session id in the interact mode
**Describe the bug**
with the scripting interface, if we do
`session = Session.interact(url_with_token, session_id, debug_no_auth=True)
`
with a correct `session_id`, things work normally.

```
But if `session_id` is not correct, we see error from the scripting interface like
Traceback (most recent call last):
  File "/Users/kswang/carta_pythonInterface_testing/test.py", line 23, in <module>
    img0 = session.open_image(image_file_0)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 630, in newfunc
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/session.py", line 371, in open_image
    return Image.new(self, path, hdu, False)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/image.py", line 68, in new
    image_id = session.call_action("appendFile" if append else "openFile", directory, file_name, hdu, return_path="frameInfo.fileId")
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/session.py", line 250, in call_action
    return self._protocol.request_scripting_action(self.session_id, path, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/protocol.py", line 362, in request_scripting_action
    raise CartaRequestFailed(f"{carta_action_description} failed with status {response.status_code}. {backend_message}")
carta.util.CartaRequestFailed: CARTA scripting action .openFile called with parameters ('/Users/kswang/carta_image_pool/set_HD163296', 'HD163296_CO_2_1.fits', '') failed with status 404. No session with ID 1070215517 could be found.
```
and the backend is still alive. However, if we correct the `session_id` and re-run the script, the backend will crash with a `Segmentation fault: 11`.

the macOS crash report is

> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000118
> Exception Codes:       0x0000000000000001, 0x0000000000000118
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
> Terminating Process:   exc handler [15944]
> 
> VM Region Info: 0x118 is not in any region.  Bytes before following region: 140737487199976
>       REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
>       UNUSED SPACE AT START
> --->  
>       VM_ALLOCATE              7fffffee6000-7fffffee7000 [    4K] r-x/r-x SM=ALI  
> 
> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   libc++.1.dylib                	    0x7ff8031aaa71 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::allocator<char> const&) + 23
> 1   carta_backend                 	       0x102b484b4 casacore::String::String(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) + 14 (String.h:257) [inlined]
> 2   carta_backend                 	       0x102b484b4 casacore::String::String(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) + 14 (String.h:257) [inlined]
> 3   carta_backend                 	       0x102b484b4 GetResolvedFilename(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 52 (Casacore.cc:104)
> 4   carta_backend                 	       0x102b05a94 carta::Session::CloseCachedImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 36 (Session.cc:2257)
> 5   carta_backend                 	       0x102b0fc94 carta::SessionManager::OnMessage(uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode) + 3684 (SessionManager.cc:258)
> 6   carta_backend                 	       0x102b178e4 ofats::any_detail::any_invocable_impl<void, false, uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode>::call(uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode) + 17 (MoveOnlyFunction.h:247) [inlined]
> 7   carta_backend                 	       0x102b178e4 ofats::any_invocable<void (uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode)>::operator()(uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode) + 17 (MoveOnlyFunction.h:354) [inlined]
> 8   carta_backend                 	       0x102b178e4 uWS::WebSocketContext<false, true, carta::PerSocketData>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*, void*) + 1300 (WebSocketContext.h:93)
> 9   carta_backend                 	       0x102b16b26 bool uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData> >::consumeMessage<6u, unsigned char>(unsigned char, char*&, unsigned int&, uWS::WebSocketState<true>*, void*) + 758 (WebSocketProtocol.h:328)
> 10  carta_backend                 	       0x102b16780 uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData> >::consume(char*, unsigned int, uWS::WebSocketState<true>*, void*) + 272 (WebSocketProtocol.h:424)
> 11  carta_backend                 	       0x102b1661a auto uWS::WebSocketContext<false, true, carta::PerSocketData>::init()::'lambda'(auto*, char*, int)::operator()<us_socket_t>(auto*, char*, int) const + 138 (WebSocketContext.h:286)
> 12  carta_backend                 	       0x102bc7b05 us_loop_run + 133 (epoll_kqueue.c:147)
> 13  carta_backend                 	       0x102b13167 uWS::Loop::run() + 8 (Loop.h:159) [inlined]
> 14  carta_backend                 	       0x102b13167 uWS::run() + 15 (Loop.h:176) [inlined]
> 15  carta_backend                 	       0x102b13167 uWS::TemplatedApp<false>::run() + 15 (App.h:393) [inlined]
> 16  carta_backend                 	       0x102b13167 carta::SessionManager::RunApp() + 343 (SessionManager.cc:572)
> 17  carta_backend                 	       0x102a591d5 main + 3877 (Main.cc:189)
> 18  dyld                          	       0x1083d052e start + 462

**To Reproduce**
1. try to use python interface to interact with an existing backend with an incorrect session id (session.interact())
2. see the carta_backend is still alive
3. fix the session id to the correct one and re-run the python script
4. carta_backend will crash

**Expected behavior**
carta_backend survives in this case

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey 
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 111
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev
 - carta-python branch: dev

### PR DESCRIPTION
**Pull request by confluence**
**Description**

This fixes #1248.

If a scripting request was made with an invalid session ID,  a null pointer was unintentionally inserted into the session manager's sessions map when the `[]` operator was used to access the map with a key which did not exist. Subsequently when a file was opened, the session manager would attempt to close cached file loaders for that file by iterating over the sessions in the map, and crash when it tried to call a function on the null pointer.

There were a few other places in the session manager code which were using the same logic -- these may never have triggered the issue because they were never called with a key that did not exist, or perhaps because if they ever were (e.g. because the session had already been deleted) if was shortly before shutdown. Nevertheless, I have replaced all of those instances as well -- all remaining instances of `_sessions[session_id]` occur while the session mutex is locked after the key is found in the map.

While I think that this change guarantees that we will never insert a null pointer into the sessions map by mistake, I'm concerned that the code doesn't currently protect against a session pointer being invalidated by the session being deleted from another thread. Fixing this would require a more careful examination of the threading logic to determine where locks (or reference counting) need to be added. I suggest discussing this in a separate issue. This particular bug was not caused by this type of race condition.

There are no companion PRs.

**Checklist**

- [x] changelog updated / no changelog update needed
- [x] e2e test passing / added corresponding fix
- [x] protobuf updated to the latest dev commit / no protobuf update needed
- [x] added reviewers and assignee
- [x] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
no regression is seen from e2e tests. Did the following manual tests and they are all good:
- one backend with multiple sessions
- session resume from dead backend, interrupted internet, slept laptop
- using a wrong session id to connect and fix the id and retry

**Review by pford — CHANGES_REQUESTED** [review]
Need a changelog update.

Other items (wait for later refactor?):

- We talked about using "find" instead of "count" for maps a while ago
- Using _sessions.at(session_id) instead of _sessions[session_id] does not insert into map, but throws an exception (std::out_of_range) if key does not exist
- Use shared_ptr for Sessions?  Instead of managing our own ref counts?

**Comment by confluence** [comment]
I will refactor this now to use `at` (much cleaner!) and to use `find` instead of `count`.

It does seem that using shared pointers is the correct thing to do here and would solve a lot of problems. I think that we should just do it, but probably in a separate PR -- it's not necessary for fixing this bug, and would require careful testing.

**Review by pford — APPROVED** [review]

**Comment by confluence** [comment]
@kswang1029 I changed the logic of the changes a little. Could you please re-run the e2e tests just in case?

**Review by kswang1029 — APPROVED** [review]
retested and it appears fine. 👍

**Pull request merged**
