### PR TITLE
Yuhsuan/issue 798 read only mode

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
This PR is for issue https://github.com/CARTAvis/carta-backend/issues/798. Changes:
* Renamed `ServerFeatureFlags::REGION_WRITE_ACCESS` to `READ_ONLY`.
* Added a `--read_only_mode` flag to enable read-only mode. Blocked writing access, including saving files (images, generated moment maps, ...), exporting regions, and writing preferences/layouts files.

### CODE REVIEW

**Comment by ajm-ska** [comment]
@YuHsuan-Hwang Is this using a special protobuffer version?

```
git submodule update --init --recursive
fatal: reference is not a tree: a7e837a583626c5a75593a0c5e0aaa1e1cacf6ca
Unable to checkout 'a7e837a583626c5a75593a0c5e0aaa1e1cacf6ca' in submodule path 'carta-protobuf'
```

**Comment by YuHsuan-Hwang** [comment]
> @YuHsuan-Hwang Is this using a special protobuffer version?
> 
> ```
> git submodule update --init --recursive
> fatal: reference is not a tree: a7e837a583626c5a75593a0c5e0aaa1e1cacf6ca
> Unable to checkout 'a7e837a583626c5a75593a0c5e0aaa1e1cacf6ca' in submodule path 'carta-protobuf'
> ```

Sorry, I just pushed the new branch. Please try again

**Comment by veggiesaurus** [comment]
> Sorry, I just pushed the new branch. Please try again

seems to work now

**Comment by veggiesaurus** [comment]
@YuHsuan-Hwang please adjust fix the `TestRestApi.cc` unit test to include the `read_only` flag

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
Unit tests need to be fixed, and it would be good to also add a test for read-only-mode, at least for the REST API. Other than that, it looks good

**Comment by YuHsuan-Hwang** [comment]
> Unit tests need to be fixed, and it would be good to also add a test for read-only-mode, at least for the REST API. Other than that, it looks good

Ok. Will try to fix the unit tests.

**Review by kswang1029 — APPROVED** [review]
as far as I can tell with a local build, the new flag `--read_only_mode` works properly. 👍

**Comment by kswang1029** [comment]
@acdo2002 this PR updates the protobuf messages, specifically the `ServerFeatureFlag` in `REGISTER_VIEWER_ACK`. Could you check if this would affect all the ICD tests?

**Comment by acdo2002** [comment]
I checkout to Yu-Hsuan's backend and Yu-Hsuan's protobuf.
Then run the current ACCESS* ICD tests, which contain `CARTA.RegisterViewer` & `CARTA.RegisterViewerAck`.
They are all working good.

**Comment by kswang1029** [comment]
> I checkout to Yu-Hsuan's backend and Yu-Hsuan's protobuf.
> Then run the current ACCESS* ICD tests, which contain `CARTA.RegisterViewer` & `CARTA.RegisterViewerAck`.
> They are all working good.

eventually we will need a test for `ServerFeatureFlag`

**Comment by YuHsuan-Hwang** [comment]
@veggiesaurus Added unit tests for read-only mode

**Review by ajm-ska — APPROVED** [review]
There is one more format error, but otherwise it can pass all the ICD tests.

**Review by markccchiang — APPROVED** [review]

**Review by confluence — APPROVED** [review]

**Pull request merged**
