### PR TITLE
610 Support for LINE, POLYLINE regions

### PR DESCRIPTION
**Pull request by pford**
Draft PR, requires frontend #1149.

Support at this stage includes region creation, import, and export.  The control points include the points in the line, allowing in many cases reuse of the polygon code, which iterates through a variable number of points.  Since these regions exist in the protobuf RegionType enum, when these regions are imported from a region file and sent to the frontend, they appear in the region list as "Not Implemented" and cannot be edited in the region dialog but can be exported along with any other regions.

Parameters such as line width are for region display (style) only, which can be set in the Appearance section of the frontend region dialog for any region type.  This aligns with the DS9 and CRTF line region definitions, which contain only the points in the line.  DS9 also supports arrow properties for a line region, not implemented here; both region file types have various region style parameters not currently supported in CARTA (TBD #340).

DS9 and CRTF region files do not support a 'polyline' region; this region type is exclusive to CARTA.  Although casacode imageanalysis includes a casa::AnnPolyline annotation region which is used in CARTA, this region is exported as 'poly' which denotes a polygon (closed region, connecting last point to first).  CARTA changes 'poly' to 'polyline' in the string produced by AnnPolyline::print.  The imageanalysis code cannot import a CRTF file containing the unknown region 'polyline', so this import is done manually.

In this implementation, the parameters necessary for spatial profiles and pV generation will be included in the future ICD messages requesting those features.

### CODE REVIEW

**Comment by zarda** [comment]
The ICD testing was updated. The exported regions_file seem not correct.

**Comment by pford** [comment]
> 
> 
> The ICD testing was updated. The exported regions_file seem not correct.

Thank you for creating this test.  The CRTF export code was not formatting the region color correctly for the imageanalysis code.  However, the test still fails, `IMPORT_REGION_ACK.regions[7].region_id = 23`, but the backend returns 24.  Is this test correct? If you have 8 regions, export world, export pix, import world (8 regions + 8 imported = 16 -- 16 expected), import pix (16 regions + 8 imported = 24 -- 23 expected).

**Comment by zarda** [comment]
The exported CRTF contains 7 regions, which may be unexpected.

**Comment by acdo2002** [comment]
I perform this together with the frontend although the "CARTA.RegionType.LINE" does not support by the current frontend.

(1) import "M17_SWex_testRegions_pix.crtf" region_Id are [1,2,3,4,5,6,7,8]
(2) export 8 regions to "M17_SWex_testRegions_pix_export_to_world.crtf"
(3) export 8 regions to "M17_SWex_testRegions_pix_export_to_pix.crtf"
(4) import "M17_SWex_testRegions_pix_export_to_world.crtf", region_Id are [9,10,11,12,13,14,15,16]
(5) import "M17_SWex_testRegions_pix_export_to_pix.crtf", region_Id are [17,18,19,20,21,22,23,24]

so IMPORT_REGION_ACK.regions[7].region_id should be "24"

So far I am curious about "POLYLINE regions". 
Since DS9 and CRTF do not support it. How to generate "POLYLINE regions" and test it with CARTA?

**Comment by pford** [comment]
> 
> So far I am curious about "POLYLINE regions".
> Since DS9 and CRTF do not support it. How to generate "POLYLINE regions" and test it with CARTA?

I exported a polygon and manually edited the CRTF and DS9 files to change "poly" or "polygon" to "polyline", then imported the region file.

**Comment by acdo2002** [comment]
Thanks Pam!!!
I follow your suggestion: manually edit them from "poly" or "polygon" to "polyline". 
Both frontend and ICD test can read the POLYLINE region (regionType of 2) from the backend return message.

**Comment by zarda** [comment]
The ICD testing could pass on a local building backend in this branch.

**Review by confluence — APPROVED** [review]
This looks OK to me.

**Review by markccchiang — APPROVED** [review]

**Comment by kswang1029** [comment]
@pford could you update this branch to date? I am testing this with the frontend PR https://github.com/CARTAvis/carta-frontend/pull/1532 but seeing inconsistency in ICD versions (and cannot request a file list).

**Comment by pford** [comment]
Updated branch with dev

**Comment by kswang1029** [comment]
@veggiesaurus @pford I have approved the corresponding frontend part https://github.com/CARTAvis/carta-frontend/pull/1532 (line region only). This can be merged together.

**Pull request merged**
