### PR TITLE
ajm/jenkinsfile timeoout

### LINKED ISSUE #1045: update the CI systems for new carta-casacore and ASAN
carta-casacore has been updated to 3.4.0+6.4.4+2022.3.9 and there is a pull request to [enable debug mode and address sanitization](https://github.com/CARTAvis/carta-backend/issues/1030). The CI systems need to be updated accordingly.

- Create RHEL7 and RHEL8 carta-casacore RPMs.

- Create 5 new Docker containers using the new carta-casacore RPM and DEB packages, plus install additional packages so that llvm-sanitizer works e.g. RHEL7 requires `clang` and `devtoolset-8-libasan-devel` to be installed

- Install new carta-casacore on the two macOS CI systems plus test that llvm-sanitizer works.

- Update the Jenkinsfile with the new flags required for the debug mode and address sanitization to work.

- Install new carta-casacore from the RHEL8 RPM on the Mix 'N Match server.

### PR DESCRIPTION
**Pull request by ajm-ska**
This doesn't fix the macOS unit test problem, but will hopefully get around one of the fail scenarios where the unit tests freeze. There are a few miscellaneous modifications too. 

The changes are as follows:

- 5 minute timeouts to the macOS unit tests.

- Increased wait time to re-run failed unit tests on macOS from 10 to 60 seconds.

- 2 hour global timeout.

- Remove the `-DCMAKE_CXX_STANDARD_LIBRARIES` and `-DOPENSSL_ROOT_DIR` flags for the M1 macOS as they are no longer necessary.
 
- Adding the `-DDevSuppressExternalWarnings=ON` flag to the macOS cmake commands.

- Updated the carta_backend flags to change `--debug_no_auth true` to `--debug_no_auth`, and `no_http true` to `--no_frontend --no_database` (I realise using true is not necessary!)

- Added new set of ICD tests; PV generator.

### CODE REVIEW

**Comment by ajm-ska** [comment]
Just to mention, this doesn't fix the problem of the yellow pending light remaining on Github indefinitely when the test suite takes more than 1 hour. Usually, it would take ~40 minutes, but if there are two commits around the same time, or a pull request is made (where it runs the test suite on the new branch and dev branch at the same time) it takes more than 1 hour. I believe the bottleneck is our Intel Mac that runs the macOS11 CI. We either need to add more macOS11 hardware in the background, consolidate the macOS11 and macOS12 systems into one (maybe just macOS12), or remove a lot of the ICD tests so the test suite passes faster (all ICD tests would still be run regularly on the long term performance test platform).

**Comment by veggiesaurus** [comment]
> or remove a lot of the ICD tests so the test suite passes faster (all ICD tests would still be run regularly on the long term performance test platform).

This problem _should_ be solved as @markccchiang migrates more ICD tests to unit tests.

**Comment by ajm-ska** [comment]
@confluence @veggiesaurus I used this existing branch to further update the Jenkinsfile with @jolopezl's address-sanitizer flags. In addition, in the background, I updated the Linux Docker containers and Mac systems with @pford's new carta-casacore 3.4.0+6.4.4+2022.3.9 branch, and the Docker containers with the ability to run `llvm-sanitizer` by installing `llvm` and `libasan`.

To each cmake flag, I appended:
```
-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -fsanitize=address -fno-omit-frame-pointer' -DCMAKE_EXE_LINKER_FLAGS='-fsanitize=address'
```

Then to the `carta_backend_tests` I prepended:
```
ASAN_OPTIONS=suppressions=${WORKSPACE}/debug/asan/myasan.supp ASAN_SYMBOLIZER_PATH=llvm-symbolizer
``` 
`${WORSPACE}` is a shortcut to get it into the appropriate carta-backend source code folder.
The `llvm-symbolizer` executable is in each Linux path by default. For MacOS, I added the specific PATH through the node settings in Jenkins itself. e.g. `:/Library/Apple/usr/bin:/opt/homebrew/Cellar/llvm/13.0.1_1/bin`. I know this is likely to change whenever Homebrew is updated. When that time comes we can just update the path in the background.

At present, the `ImageExprFails` Unit Test is failing. @pford previously noted this would happen. However, it is a good test for now to show how the new ASAN feature behaves. You can see all the debug output at the end of each _detail.xml file. So it will not pass any tests at the moment, so no need to merge it just yet.
Screen Shot 2022-03-13 at 4 56 49 PM

I noticed that there was an Ubuntu 22.04 Docker image available, so I took the opportunity to make a 22.04 Docker container. I'm calling is `ajmasiaa/jammy-beta-jenkins-mar2022`. When the final release 22.04 is out, we will be able to change the container in the background without needing to modify the Jenkinsfile again.

**Comment by ajm-ska** [comment]
@confluence I have just switched the Linux Docker containers back to the old ones for now so that other branches will continue to build successfully. It appears the new Docker containers require more testing because there is various trouble with the ICD tests. Some ICD tests are failing, and I need to install a newer `npm` in Ubuntu 18.04. So I'll need to manually test everything in each one first.

I'll just leave 2 macOS systems with the new carta-casacore so the `ImageExprTest.ImageExprFails` Unit Test will fail. I'll announce it on Slack.

**Comment by confluence** [comment]
It looks like dev needs to be merged into this branch.

If these changes are still needed, I'm happy to approve this if dev is merged and the conflicts are resolved.

**Comment by ajm-ska** [comment]
@confluence OK. I'm hoping the `Jenkinsfile` in this branch will become the new `Jenkinsfile-full` that will only be run on the `dev` branch once per day. But I'm still in the process of trying to sort out all the errors that the Address Sanitizer introduced when running the ICD tests.

**Comment by confluence** [comment]
OK. Should this be a draft in the meantime?

**Comment by ajm-ska** [comment]
OK. Although I'm very close now. I'm just going to temporarily skip the ICD tests that have revealed Address Sanitizer built carta-backend problems. The problems have been raised as Github issues. Then we can add the ICD tests back later once the carta-backend problems have been fixed.

**Comment by ajm-ska** [comment]
@confluence @veggiesaurus We can try merging this branch now. `Jenkinsfile-full` should now contain the full test suite, but with some caveats:

- Due to the new carta-casacore, the `ImageExprTest.ImageExprFails` Unit Test fails, so I have temporarily deactivated that test on all 7 platforms: `--gtest_filter=-ImageExprTest.ImageExprFails`

- Due to the ICD region test problem only on RHEL8 (issue #909 ), I rebuilt its carta-casacore with the `-U_GLIBCXX_ASSERTIONS` flag. That gets around the problem but leads to another problem of the `MomentTest.CheckConsistencyForBeamConvolutions` Unit Test failing. So on RHEL8, I have also temporarily deactivated that unit test.

- The strict debugging introduced by the Address Sanitizer flags regularly leads to failures in the following ICD test stages:
1. Region Manipulation ICD tests (issue #1066)
2. Cube Histogram (issue #1051)
3. Moments (issue #1070)

    So I am temporarily skipping those ICD tests. Jenkins will indicate that the tests have passed, but they have actually been skipped. It prints a note that the tests are temporarily skipped: ```*** Temporarily skipping tests *** ```. Once the related backend issues are fixed, we can re-introduce the skipped tests.

- It appears that there will still be an occasional failure in the Resume and Close File tests. The Close File error was reported as issue #1052. But the failures are quite rare so I'm taking a chance to leave those tests activated for now.

- Unit tests occasionally fail on macOS12. It is a known issue and also occurs on the short Jenkinsfile (build and unit tests on 3 platforms).

Once this updated `Jenkinsfile-full` file is merged, I will try to set up a new Jenkins job that will only run this file once a day on the `dev` branch as we had planned.

**Review by confluence — APPROVED** [review]

**Pull request merged**
