### PR TITLE
757 Use casacore FitsInput for FITS headers

### LINKED ISSUE #757: Support SIP (standard imaging polynomials) in WCS?
It seems that CARTA does not support standard imaging polynomials that model the distortion with respect to the projection. My [FITS file](https://github.com/CARTAvis/carta/files/6076445/FF_NL000D_20201205_182427_194_0200448.fits.zip) contains `RA---ZEA-SIP` as WCS-projection, however the coordinate overlay seems to give wrong coordinates further away from the center of the image. See the screenshots of a catalog overlay in both CARTA and DS9, where I tried to highlight the same pixel (378, 84) in both images to show the RA/DEC coordinates.

It would be nice if SIP would be supported, or if a warning is given if the SIP are being ignored.

ds9-sip
carta-sip

### PR DESCRIPTION
**Pull request by pford**
Closes #757 

The backend will always use casacore::FitsInput (cfitsio interface) for FITS files to show actual headers in file info.  Specifically for this issue, the CTYPE and projection string will include the "SIP" suffix for use by the frontend.

This change breaks FILEINFO_FITS.test.ts since some file info header entries have changed. For example, keyword "PC1_1" is now "PC01_01" for set_QA/M17_SWex.fits.

### CODE REVIEW

**Review by confluence — APPROVED** [review]

**Comment by kswang1029** [comment]
@pford  this also fixes #460 ?

**Comment by pford** [comment]
@kswang1029 this is for FITS only but yes the actual headers are displayed and used for computed entries in the file info.  For #460 I can look into reading the HDF5 headers; we already have this implemented, for creating the CartaHdf5Image.

**Comment by kswang1029** [comment]
> @kswang1029 this is for FITS only but yes the actual headers are displayed and used for computed entries in the file info. For #460 I can look into reading the HDF5 headers; we already have this implemented, for creating the CartaHdf5Image.

This is great! Thank you 🙂 I guess this will remove some ambiguities with FITS images.

**Review by markccchiang — APPROVED** [review]

**Comment by pford** [comment]
Found a computed entries issue with test images in #460, converted to draft PR.

**Comment by pford** [comment]
Fixed the issue.  I think the casacore CoordinateSystem treats a velocity axis as Linear instead of Spectral, so when the FileLoader found Linear+Stokes axes it assumed it was a PV image and set the render axes to linear/stokes.  Now it looks for direction axes first.  Moved PR back to Open.

**Comment by veggiesaurus** [comment]
@kswang1029 can you test this? Code looks fine to merge

**Comment by kswang1029** [comment]
Found a rendering issue which should not be related to this PR. For a header like this, somehow the frontend switches to the flexible pixel aspect ratio mode. It might be because CUNIT is missing in the FITS header. @veggiesaurus is it possible that we can schedule a quick fix on the frontend?

> XTENSION= 'IMAGE   '           / Java FITS: Wed Oct 01 10:15:59 CEST 2014       
BITPIX  =                  -64                                                  
NAXIS   =                    2 / Dimensionality                                 
NAXIS1  =                  830                                                  
NAXIS2  =                  870                                                  
PCOUNT  =                    0 / No extra parameters                            
GCOUNT  =                    1 / One group                                      
LONGSTRN= 'OGIP 1.0'           / The OGIP long string convention may be used.   
COMMENT This FITS file may contain long string keyword values that are          
COMMENT continued over multiple keywords.  This convention uses the  '&'        
COMMENT character at the end of a string which is then continued                
COMMENT on subsequent keywords whose name = 'CONTINUE'.                         
          -------------- Herschel Structure Data--------------------            
          Following fields are private to the structure of the                  
          Java object this HDU is representing.                                 
EXTNAME = 'image   '           / name of this HDU                               
CLASS___= 'herschel.ia.dataset.ArrayDataset' / java representation              
INFO____= 'Image   '                                                            
DATA____= 'herschel.ia.numeric.Double2d' / java Data                            
QTTY____= 'MJy/sr  '           / Unit of the data                               
BUNIT   = 'MJy/sr  '           / Unit of the data                               
          -------------- Herschel Parameter Data--------------------            
          All actual parameter names are converted to FITS compliant            
          conventions. Note that the HIERARCH comments contain the              
          appropriate key mapping                                               
META_0  =                    2 / [] WCS: Number of Axes                         
CRPIX1  =                371.0 / [] WCS: Reference pixel position axis 1, uni&  
COMMENT t=Scalar                                                                
CRPIX2  =                421.0 / [] WCS: Reference pixel position axis 2, uni&  
COMMENT t=Scalar                                                                
CRVAL1  =   107.30461727023817 / [] WCS: First coordinate of reference pixel    
CRVAL2  =  -10.610720896516849 / [] WCS: Second coordinate of reference pixel   
CDELT1  =   -0.003888888888889 / [] WCS: Pixel scale axis 1, unit=Angle         
CDELT2  =    0.003888888888889 / [] WCS: Pixel scale axis 2, unit=Angle         
CTYPE1  = 'RA---TAN'           / WCS: Projection type axis 1, default="LINEAR"  
CTYPE2  = 'DEC--TAN'           / WCS: Projection type axis 2, default="LINEAR"  
EQUINOX =               2000.0 / [] WCS: Equinox, unit=Duration                 
CROTA2  =                  0.0 / [] The Rotation angle                          
META_1  =                  830 / [] The number of columns                       
META_2  =                  870 / [] The number of rows              

spire500_ext fits-image-2021-06-22-13-51-36


one more example:
h_m51_b_s05_drz_sci fits-image-2021-06-22-13-59-46

**Comment by kswang1029** [comment]
@pford please wait a bit for the frontend issue fixed. Then I will do more tests to double-check there is no other unexpected issues.

**Comment by veggiesaurus** [comment]
> @pford please wait a bit for the frontend issue fixed. Then I will do more tests to double-check there is no other unexpected issues.

@kswang1029 please retest, I think I've fixed the rendering issue

**Comment by veggiesaurus** [comment]
@pford can you fix the merge conflicts here? I think they're mostly conflicting with your HDF5 branch, which has now been merged into `dev`.

**Comment by kswang1029** [comment]
@pford could you help me to update your branch and solve conflicts? The ICD version needs an update otherwise with the dev frontend (with aspect ratio problem solved) we cannot load images for testing.

**Comment by pford** [comment]
Updated branch, ready to test.

**Review by kswang1029 — APPROVED** [review]
Good to go! This should make FITS users happier. 👍

**Pull request merged**
