### PR TITLE
Support DS9 file with no header

### LINKED ISSUE #1064: Region handling: some valid ds9 regions are not supported
I encountered an issue where a region file formatted like this:
```
icrs
point(17:25:26.34, -28:30:40.54) # point=x
```
is not recognized as a region file by CARTA, but it is a valid ds9 region file.

### PR DESCRIPTION
**Pull request by pford**
Closes #1064 

For the region file list, carta reads the first line to look for the expected CRTF or DS9 header.  When the optional DS9 header line is missing, the carta file type is unknown; with this change, the extension is checked to determine the file type.  If the region file does not have the header or extension to indicate its type, it is not recognized by the file browser.

### CODE REVIEW

**Comment by pford** [comment]
Note: the other import issues with region properties described in #1064 were fixed in PR #1135

**Review by kswang1029 — CHANGES_REQUESTED** [review]
@pford on my dev environment, when I click "Import regions" from the File menu, the backend will crash. The backend shows "libc++abi: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6"
This was caught by e2e tests and confirmed manually too.

It seems to be parsing a catalog file in xml (VOTable). Please try the attached files to reproduce the issue by loading the image first and try to click "import regions" to crash the backend.

[tmp.zip](https://github.com/CARTAvis/carta-backend/files/9078797/tmp.zip)



macOS console shows the log:

Thread 2 Crashed:
0   libsystem_kernel.dylib        	    0x7ff81876200e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8187981ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8186e3d24 abort + 123
3   libc++abi.dylib               	    0x7ff818754082 abort_message + 241
4   libc++abi.dylib               	    0x7ff8187451a5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	    0x7ff818641e19 _objc_terminate() + 104
6   libc++abi.dylib               	    0x7ff8187534a7 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	    0x7ff818755d05 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	    0x7ff818755ccc __cxa_throw + 116
9   libc++.1.dylib                	    0x7ff8186f9a34 std::__1::__throw_out_of_range(char const*) + 56
10  libc++.1.dylib                	    0x7ff8186f99fc std::__1::__basic_string_common<true>::__throw_out_of_range() const + 16
11  libc++.1.dylib                	    0x7ff8186f9c1d std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_out_of_range() const + 9
12  libc++.1.dylib                	    0x7ff8186faae8 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::allocator<char> const&) + 174
13  carta_backend                 	       0x10085ae4d std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::substr(unsigned long, unsigned long) const + 18 (string:3512) [inlined]
14  carta_backend                 	       0x10085ae4d carta::RegionImportExport::ParseRegionParameters(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) + 2221 (RegionImportExport.cc:216)
15  carta_backend                 	       0x10081bd46 carta::Ds9ImportExport::SetRegion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 102 (Ds9ImportExport.cc:337)
16  carta_backend                 	       0x10081752d carta::Ds9ImportExport::ProcessFileLines(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) + 429 (Ds9ImportExport.cc:237)
17  carta_backend                 	       0x100817208 carta::Ds9ImportExport::Ds9ImportExport(std::__1::shared_ptr<casacore::CoordinateSystem>, casacore::IPosition const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 328 (Ds9ImportExport.cc:29)
18  carta_backend                 	       0x10066f7f0 carta::FileListHandler::IsDs9FileNoHeader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 96 (FileListHandler.cc:295)
19  carta_backend                 	       0x10066e97a carta::FileListHandler::GetFileList(CARTA::FileListResponse&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, carta::FileListHandler::ResultMsg&, CARTA::FileListFilterMode, bool) + 2218 (FileListHandler.cc:154)
20  carta_backend                 	       0x10066fe00 carta::FileListHandler::OnRegionListRequest(CARTA::RegionListRequest const&, CARTA::RegionListResponse&, carta::FileListHandler::ResultMsg&) + 704 (FileListHandler.cc:274)
21  carta_backend                 	       0x10086e88b carta::Session::OnRegionListRequest(CARTA::RegionListRequest const&, unsigned int) + 283 (Session.cc:439)
22  carta_backend                 	       0x100894ec7 carta::GeneralMessageTask<CARTA::RegionListRequest>::execute() + 23 (OnMessageTask.tcc:30)
23  carta_backend                 	       0x1008c7341 carta::ThreadManager::StartEventHandlingThreads(int)::$_0::operator()() const + 114 (ThreadingManager.cc:54) [inlined]
24  carta_backend                 	       0x1008c7341 decltype(static_cast<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(fp)()) std::__1::__invoke<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(carta::ThreadManager::StartEventHandlingThreads(int)::$_0&&) + 114 (type_traits:3918) [inlined]
25  carta_backend                 	       0x1008c7341 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>&, std::__1::__tuple_indices<>) + 114 (thread:287) [inlined]
26  carta_backend                 	       0x1008c7341 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0> >(void*) + 177 (thread:298)
27  libsystem_pthread.dylib       	    0x7ff8187984e1 _pthread_start + 125
28  libsystem_pthread.dylib       	    0x7ff818793f6b thread_start + 15

**Comment by pford** [comment]
@kswang1029 I added a fix for the crash when parsing non-region files.  Please test again.

**Comment by kswang1029** [comment]
@pford yes the crash issue is gone. The region e2e tests are still failing as it takes few seconds to generate the file list after clicking "import regions". Any possibility to improve this? 

files in the directory
Screen Shot 2022-07-12 at 10 10 36


v3b3:

https://user-images.githubusercontent.com/20819712/178393854-c7e6f2a5-9666-43f2-8dc0-4ddc43e96a49.mov

[05e7a64](https://github.com/CARTAvis/carta-backend/pull/1142/commits/05e7a6402912b51452c1407506c94afb2b581637):


https://user-images.githubusercontent.com/20819712/178393888-bd75e906-917f-4825-bddc-1698fe7ff190.mov

**Comment by pford** [comment]
I removed the file parsing, which took too long with a long file list.  Now it just checks the first line for the header, then the extension, to include the file in the region file browser.

**Review by kswang1029 — APPROVED** [review]
e2e tests are all passing. I added one e2e test for this use case and will enable it on e2e CI once this PR is merged. Manual test appears fine. No performance impact is observed. 👍

**Review by markccchiang — APPROVED** [review]

**Review by confluence — APPROVED** [review]

**Pull request merged**
