### PR TITLE
Log adjustments

### LINKED ISSUE #751: Log adjustments
Some small adjustments to the logging code:

* Change the level of performance messages to debug
* Log performance to a separate file
* Flush logs regularly
* Flush logs before exiting
* Misc. refactoring

### PR DESCRIPTION
**Pull request by confluence**
Various logging adjustments. Should fix #751.

### CODE REVIEW

**Review by veggiesaurus — APPROVED** [review]

**Comment by veggiesaurus** [comment]
code looks fine, @kswang1029 please let me know when you've checked the output format

**Comment by confluence** [comment]
I haven't had a chance to remove / refactor the tile message -- do we still want to do that?

**Comment by veggiesaurus** [comment]
> I haven't had a chance to remove / refactor the tile message -- do we still want to do that?

that can be a separate issue assigned to @zarda I guess? I think he wrote the original performance logging stuff.

**Comment by kswang1029** [comment]
@confluence @veggiesaurus with `--verbosity 5 --log_performance --log_protocol_messages`, I see performance and protocol message log from the terminal. Performance logs are saved in a separate file. 👍

**Pull request merged**
