### PR TITLE
Update the submodule uWebSockets

### LINKED ISSUE #1297: Update the uWebSockets
It has been more than two years since the latest update of the submodule uWebSockets. The new version of uWebSockets also includes the fix of the warning message of deprecated C syntax from the Mac Xcode (14.2). So we may be better to catch up with it.

### PR DESCRIPTION
**Pull request by markccchiang**
**Description**

* What is implemented or fixed? Mention the linked issue(s), if any.
Closes #1297.

* How does this PR solve the issue? Give a brief summary.
Update the uWebSockets to the latest version and fix the warning of deprecated C syntax from Mac Xcode.

* Are there any companion PRs (frontend, protobuf)?
No.

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Everything should not be affected.

**Checklist**

- [x] changelog updated ~/ no changelog update needed~
- [ ] e2e test passing / ~added corresponding fix~
- [x] ~protobuf updated to the latest dev commit /~ no protobuf update needed
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Comment by kswang1029** [comment]
@markccchiang @ajm-asiaa  what's the procedure of updating uWebSockets then? Any risks/impacts to the v4-stable release?

**Comment by markccchiang** [comment]
> @markccchiang @ajm-asiaa what's the procedure of updating uWebSockets then? Any risks/impacts to the v4-stable release?

@kswang1029 You can just check out this branch, and run `git submodule update --init --recursive` to download extra files from uWebSocket, then rebuild the backend as usual. I think there are no risks/impacts to the v4-stable release, but it needs more tests.

**Comment by markccchiang** [comment]
> > @markccchiang @ajm-asiaa what's the procedure of updating uWebSockets then? Any risks/impacts to the v4-stable release?
> 
> @kswang1029 You can just check out this branch, and run `git submodule update --init --recursive` to download extra files from uWebSocket, then rebuild the backend as usual. I think there are no risks/impacts to the v4-stable release, but it needs more tests.

**Review by kswang1029 — APPROVED** [review]
I used e2e test suite to test this PR with the following two platforms:
- macOS Ventura (arm64) with Xcode Version 14.2 (14C18)
- Ubuntu (x86_64)
The tests are fine in these two platforms.

Please proceed code review.

**Comment by ajm-ska** [comment]
@markccchiang I notice the new uWebSockets downloads 822MB into `/third-party/uWebSockets`, whereas the old uWebSockets only needs to download 2.2MB. 
Is it necessary to download so much data?
It makes the `git submodule update --init --recursive` step slower, and occupies a lot more space. It is not so good for CI.

For the old one it only clones the following: 
```
Submodule path 'uWebSockets': checked out 'b7c82d791010bd4c9b45528846f95b9886e9f984'
Submodule 'fuzzing/libEpollFuzzer' (https://github.com/uNetworking/libEpollFuzzer) registered for path 'uWebSockets/fuzzing/libEpollFuzzer'
Submodule 'libdeflate' (https://github.com/ebiggers/libdeflate) registered for path 'uWebSockets/libdeflate'
Submodule 'uSockets' (https://github.com/uNetworking/uSockets.git) registered for path 'uWebSockets/uSockets'
Cloning into '/home/acdc/carta-backend3/third-party/uWebSockets/fuzzing/libEpollFuzzer'...
Cloning into '/home/acdc/carta-backend3/third-party/uWebSockets/libdeflate'...
Cloning into '/home/acdc/carta-backend3/third-party/uWebSockets/uSockets'...
Submodule path 'uWebSockets/fuzzing/libEpollFuzzer': checked out 'b9bbd2d490a2fe3784283e0e456381ff26f175d6'
Submodule path 'uWebSockets/libdeflate': checked out '4d3c0f00d55c3bfd7abe3f7ac3d99e3bd0f7f96b'
Submodule path 'uWebSockets/uSockets': checked out '5440dbac79bd76444175b76ee95dfcade12a6aac'
```
For the new one, it seems to clone a lot more components:
```
Submodule path 'uWebSockets': checked out '3bb917da2e44f36a5fec32d735cb61839fe1cc6c'
Submodule 'fuzzing/libEpollFuzzer' (https://github.com/uNetworking/libEpollFuzzer) registered for path 'uWebSockets/fuzzing/libEpollFuzzer'
Submodule 'fuzzing/seed-corpus' (https://github.com/uNetworking/seed-corpus.git) registered for path 'uWebSockets/fuzzing/seed-corpus'
Submodule 'uSockets' (https://github.com/uNetworking/uSockets.git) registered for path 'uWebSockets/uSockets'
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/fuzzing/libEpollFuzzer'...
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/fuzzing/seed-corpus'...
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/uSockets'...
Submodule path 'uWebSockets/fuzzing/libEpollFuzzer': checked out 'b9bbd2d490a2fe3784283e0e456381ff26f175d6'
Submodule path 'uWebSockets/fuzzing/seed-corpus': checked out '69f5fd36c102f0a7d527049983c0e2b2a822c23d'
Submodule path 'uWebSockets/uSockets': checked out '8cd4cb66eb061b2594ca114b9ea1ead64613ad4b'
Submodule 'boringssl' (https://github.com/google/boringssl) registered for path 'uWebSockets/uSockets/boringssl'
Submodule 'lsquic' (https://github.com/litespeedtech/lsquic) registered for path 'uWebSockets/uSockets/lsquic'
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/uSockets/boringssl'...
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/uSockets/lsquic'...
Submodule path 'uWebSockets/uSockets/boringssl': checked out '1ccef4908ce04adc6d246262846f3cd8a111fa44'
Submodule path 'uWebSockets/uSockets/lsquic': checked out '108c4e7629a8c10b9a73e3d95be0a1652e620fb9'
Submodule 'src/liblsquic/ls-qpack' (https://github.com/litespeedtech/ls-qpack) registered for path 'uWebSockets/uSockets/lsquic/src/liblsquic/ls-qpack'
Submodule 'src/lshpack' (https://github.com/litespeedtech/ls-hpack) registered for path 'uWebSockets/uSockets/lsquic/src/lshpack'
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/uSockets/lsquic/src/liblsquic/ls-qpack'...
Cloning into '/home/acdc/carta-backend4/third-party/uWebSockets/uSockets/lsquic/src/lshpack'...
Submodule path 'uWebSockets/uSockets/lsquic/src/liblsquic/ls-qpack': checked out 'ba02bf55e108d60e87d4d204072ef69b063548ca'
Submodule path 'uWebSockets/uSockets/lsquic/src/lshpack': checked out '14bec45020023db299b0a2c12a0c9ac90fbed49b'
```
Are all those new components necessary?

**Comment by markccchiang** [comment]
> @markccchiang I notice the new uWebSockets downloads 822MB into `/third-party/uWebSockets`, whereas the old uWebSockets only needs to download 2.2MB. Is it necessary to download so much data? It makes the `git submodule update --init --recursive` step slower, and occupies a lot more space. It is not so good for CI.
> 

@ajm-asiaa The new uWebSockets has included many massive submodules. But we only need one submodule `uSocket`. So instead of using the git command `git submodule update --init --recursive`, we can use `git submodule update --init uSockets` under the `uWebSockets` folder. But I am not sure is it convenient to download the other submodules in the backend repo without using the `--recursive` argument?

**Comment by ajm-ska** [comment]
@markccchiang I had a quick look at the uWebSockets repository. Is uSockets a submodule of uWebsockets?
https://github.com/uNetworking/uWebSockets
https://github.com/uNetworking/uSockets
If so, could we just grab uSockets instead?

If not, do you think we could fork the uWebSockets repository? They already have 1.7k forks. Then we could delete the unused parts. I guess forking it would be OK seeing that we don't update it very often.

**Comment by markccchiang** [comment]
> @markccchiang I had a quick look at the uWebSockets repository. Is uSockets a submodule of uWebsockets? https://github.com/uNetworking/uWebSockets https://github.com/uNetworking/uSockets If so, could we just grab uSockets instead?
> 
> If not, do you think we could fork the uWebSockets repository? They already have 1.7k forks. Then we could delete the unused parts. I guess forking it would be OK seeing that we don't update it very often.

@ajm-asiaa Yes, uSockets is a submodule of uWebsockets. Forking the uWebSockets and deleting unused submodules is also a good way. Which way do you prefer?

**Comment by ajm-ska** [comment]
@markccchiang I just tried the first idea of using the uSockets submodule instead of uWebSockets, but I don't think it will work. I see Session.h needs to include <uWebSockets/App.h>, but there is no uSockets/src/App.h.
So unless I missed something, I think the only way is to fork uWebsockets and delete the unused submodules.

**Comment by markccchiang** [comment]
> @markccchiang I just tried the first idea of using the uSockets submodule instead of uWebSockets, but I don't think it will work. I see Session.h needs to include <uWebSockets/App.h>, but there is no uSockets/src/App.h. So unless I missed something, I think the only way is to fork uWebsockets and delete the unused submodules.

@ajm-asiaa Ok. So I will try to fork uWebsockets and uSocket under the CARTAvis account and remove unused submodules from them. And then use them as new submodules for the backend.

**Review by ajm-ska — APPROVED** [review]
@markccchiang Thank you for doing the uWebSockets fork approach. That is a lot better. Now it only needs to download 1.4MB rather than 822MB!
I have run your branch through the full ICD test suite and it can pass on all platforms, so everything seems to be OK.

**Review by kswang1029 — APPROVED** [review]
the new lightweight solutions work fine. no regression from e2e tests.

**Comment by veggiesaurus** [comment]
I really don't want us to maintain a fork simply for reducing download size.

An alternative suggestion: use a third-party CMake dependency instead of a submodule, and just grab the source archive from the release URL (https://github.com/uNetworking/uWebSockets/archive/refs/tags/v20.45.0.zip). More information here: https://cmake.org/cmake/help/v3.6/module/ExternalProject.html

We could probably take this approach with lots of other packages

**Comment by markccchiang** [comment]
@ajm-asiaa The new CMake script downloads zip files of `uWebSockets` and `uSockets`, unpackages them, and compiles them during the build of the backend. However, it failed on `AlmaLinux-8`, not sure the reason why. Could you please check if the build of `uSocket` is successful, i.e., the file `carta-backend/carta-backend/third-party/uSockets/uSockets.a` does exist?

**Comment by ajm-ska** [comment]
@markccchiang First I checked to see if there is something wrong with the CI server. The `AlmaLinux-8` CI builds natively on one of our servers using self-hosted Github Actions runner. I just tried building the branch using an AlmaLinux-8 Docker container (ajmasiaa/rhel8-jenkins-apr2022) on another server. It gives exactly the same problem. Therefore, there must be something wrong with the code.

The `uSockets.a` does exist, but I think it may not have built properly.

I'm not sure if the following is the proper way to test it, but in the carta-backend build log, I see this, for example, 

>  undefined reference to `us_socket_ext'

On the Ubuntu server, where the CI was successful, I ran this `nm -s uSockets.a | grep us_socket_ext`. 
It shows `00000000 T us_socket_ext`
However, when I do the same on the AlmaLinux8 server, it does not show that.

It is strange, that on both servers, the `uSockets.a` is the same file size: 234176 bytes. But when I inspect them with nm, the AlmaLinux8 one has much fewer lines.

I wonder if it could be something to do with the cmake or gcc versions? 
almalinux8 - cmake 3.20.2 - gcc 8.5.0
ubuntu - cmake 3.16.3 - gcc 9.4.0.
Although I would be surprised because the uWebscokets/uSockets build is very basic.

**Comment by ajm-ska** [comment]
@markccchiang I found something. If I do "make" in the `third-party/uSocket` folder on the Ubuntu server, I get:
> rm -f *.o
> cc -flto -DLIBUS_NO_SSL -std=c11 -Isrc -O3 -c src/*.c src/eventing/*.c src/crypto/*.c src/io_uring/*.c
> lib.exe /out:uSockets.a *.o || ar rvs uSockets.a *.o
> /bin/sh: 1: lib.exe: not found
> r - bsd.o
> r - context.o
> r - epoll_kqueue.o
> r - gcd.o
> r - io_context.o
> r - io_loop.o
> r - io_socket.o
> r - libuv.o
> r - loop.o
> r - openssl.o
> r - quic.o
> r - socket.o
> r - udp.o

But if I do the same on the AlmaLinux8 server, I get:
> rm -f *.o
> cc -flto -DLIBUS_NO_SSL -std=c11 -Isrc -O3 -c src/*.c src/eventing/*.c src/crypto/*.c src/io_uring/*.c
> lib.exe /out:uSockets.a *.o || ar rvs uSockets.a *.o
> /bin/sh: lib.exe: command not found
> r - bsd.o
> r - context.o
> r - epoll_kqueue.o
> r - gcd.o
> r - io_context.o
> r - io_loop.o
> r - io_socket.o
> r - libuv.o
> r - loop.o
> r - openssl.o
> r - quic.o
> r - socket.o
> r - udp.o
> ar: bsd.o: plugin needed to handle lto object
> ar: context.o: plugin needed to handle lto object
> ar: epoll_kqueue.o: plugin needed to handle lto object
> ar: gcd.o: plugin needed to handle lto object
> ar: io_context.o: plugin needed to handle lto object
> ar: io_loop.o: plugin needed to handle lto object
> ar: io_socket.o: plugin needed to handle lto object
> ar: libuv.o: plugin needed to handle lto object
> ar: loop.o: plugin needed to handle lto object
> ar: openssl.o: plugin needed to handle lto object
> ar: quic.o: plugin needed to handle lto object
> ar: socket.o: plugin needed to handle lto object
> ar: udp.o: plugin needed to handle lto object

So it seems "ar" on AlmaLinux8 is not working as expected.

**Comment by ajm-ska** [comment]
@markccchiang It looks like someone had the exact same problem before: https://github.com/uNetworking/uWebSockets/discussions/1373

**Comment by markccchiang** [comment]
> @markccchiang It looks like someone had the exact same problem before: [uNetworking/uWebSockets#1373](https://github.com/uNetworking/uWebSockets/discussions/1373)

@ajm-asiaa Thank you so much for quickly spotting the root cause of this problem! Ideally, we want to download uWebSockets/uSockets source codes and compile them in a single CMake command. If we can not use `git clone --init --recursive` beforehand. But CMake can not configure source code files that do not exist (before they are downloaded). So we can only use the function ExternalProject() from CMake to download and build it. But this way has a problem that we can not control how to compile them like we encountered on AlmaLinux8.

**Comment by markccchiang** [comment]
> @ajm-asiaa Thank you so much for quickly spotting the root cause of this problem! Ideally, we want to download uWebSockets/uSockets source codes and compile them in a single CMake command. If we can not use `git clone --init --recursive` beforehand. But CMake can not configure source code files that do not exist (before they are downloaded). So we can only use the function ExternalProject() from CMake to download and build it. But this way has a problem that we can not control how to compile them like we encountered on AlmaLinux8.

Looks like `FetchContent` methods from the CMake are promising. It can exactly do the things we want.

**Review by ajm-ska — APPROVED** [review]
I ran this branch on the full ICD test suite. The carta-backend still builds and runs fine on all platforms.

**Review by confluence — APPROVED** [review]

**Comment by kswang1029** [comment]
@markccchiang on macOS, with `cmake` I see 

> CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FetchContent.cmake:1282 (message):
>   The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
>   not set.  The policy's OLD behavior will be used.  When using a URL
>   download, the timestamps of extracted files should preferably be that of
>   the time of extraction, otherwise code that depends on the extracted
>   contents might not be rebuilt if the URL changes.  The OLD behavior
>   preserves the timestamps from the archive instead, but this is usually not
>   what you want.  Update your project to the NEW behavior or specify the
>   DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
>   robustness issue.
> Call Stack (most recent call first):
>   third-party/install/uWebSockets.cmake:7 (FetchContent_Declare)
>   CMakeLists.txt:159 (install_uWebSockets)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FetchContent.cmake:1282 (message):
>   The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
>   not set.  The policy's OLD behavior will be used.  When using a URL
>   download, the timestamps of extracted files should preferably be that of
>   the time of extraction, otherwise code that depends on the extracted
>   contents might not be rebuilt if the URL changes.  The OLD behavior
>   preserves the timestamps from the archive instead, but this is usually not
>   what you want.  Update your project to the NEW behavior or specify the
>   DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
>   robustness issue.
> Call Stack (most recent call first):
>   third-party/install/uWebSockets.cmake:38 (FetchContent_Declare)
>   CMakeLists.txt:159 (install_uWebSockets)
> This warning is for project developers.  Use -Wno-dev to suppress it.


The backend can be built successfully though. Any idea to get rid of those warnings?

**Review by kswang1029 — APPROVED** [review]

**Pull request merged**
