### PR TITLE
Angus/workspace update

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**
Trivial change to support workspace sharing PR https://github.com/CARTAvis/carta-controller/pull/155

### CODE REVIEW

**Comment by kswang1029** [comment]
With dev+dev, I have a restorable workspace. With the branch, however, the backend crashes when I select the workspace file in the file browser. The backend log shows:

> [2023-08-22 00:17:00.381] [CARTA] [critical] [json.exception.type_error.302] type must be boolean, but is null

**Review by kswang1029 — CHANGES_REQUESTED** [review]
With dev+dev, I have a restorable workspace. With this branch, however, the backend crashes when I select the workspace file in the file browser. The backend log shows:

> [2023-08-22 00:17:00.381] [CARTA] [critical] [json.exception.type_error.302] type must be boolean, but is null


With this branch, when I try to save a workspace, there is an error saying the workspace cannot be saved but in the file list I see the workspace name shows up and in `.carta` folder I do see the (non-empty) workspace json file which actually can be restored with dev+dev. If I try to restore it with this branch, again the backend crashes.

**Comment by veggiesaurus** [comment]
> With dev+dev, I have a restorable workspace. With this branch, however, the backend crashes when I select the workspace file in the file browser. The backend log shows:
> 
> > [2023-08-22 00:17:00.381] [CARTA] [critical] [json.exception.type_error.302] type must be boolean, but is null
> 

Fixed, sorry about that.

> With this branch, when I try to save a workspace, there is an error saying the workspace cannot be saved but in the file list I see the workspace name shows up and in `.carta` folder I do see the (non-empty) workspace json file which actually can be restored with dev+dev. If I try to restore it with this branch, again the backend crashes.

I can reproduce this, but think it is a frontend bug. I will try fix it there quickly.

**Comment by veggiesaurus** [comment]
@kswang1029 can you retry with this branch and the latest commit of the frontend branch?

**Comment by kswang1029** [comment]
> @kswang1029 can you retry with this branch and the latest commit of the frontend branch?

Yes, the issues are gone~ Will proceed tests including the controller.

**Review by kswang1029 — APPROVED** [review]

**Review by ajm-ska — APPROVED** [review]
Tested and works well!

**Pull request merged**
