### PR TITLE
Yuhsuan/150 fitting enhancement

### LINKED ISSUE #150: 2d image fitting
related frontend issue https://github.com/CARTAvis/carta-frontend/issues/1397

This is to provide users the ability to select a region and fit a 2D function such as 2D Gaussian to get feature properties. Note that full resolution image data need to be used as fitting input, instead of downsampled data.

Requirement document:
https://docs.google.com/document/d/1E9kL7FOhVtkDDit8VIYle61tU5PzSYXjnLpxZBCHliY/edit?usp=sharing

Implementation plan:
- [x] Basic single/multiple gaussian fitting and text outputs
- [x] Gaussian fitting with fixed initial values
- [x] Gaussian fitting of the current view in frontend
---- target for v3b3 ----
- [x] Output model/residual images
- [x] Estimate progress and listen for cancellation messages
- [ ] Gaussian fitting of selected regions
- [ ] support a background level in the fitting
- [ ] support different solvers in the fitting
- [X] ~also use beam deconvolved image as the input data for fitting~ moved to new issue https://github.com/CARTAvis/carta-backend/issues/1236

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

Closes #150 remaining enhancement items in the image fitting feature. Requiring frontend PR https://github.com/CARTAvis/carta-frontend/pull/2094 and protobuf PR https://github.com/CARTAvis/carta-protobuf/pull/81.

~Frontend PR still in progress.~

Changes
 - Support fitting with created regions. Fails if the region id is negative or unfound.
 - Support fitting with a background offset as a constant or a free parameter. If the value is not provided in the protobuf message, the default offset is 0. If the fixed parameter array length is invalid, the default is fixed.
 - Support fitting with different solvers. `mcholesky` is not supported because it's not available in all gsl versions. If the solver type is not provided in the protobuf message, the default is Cholesky.
 - Check for length of the fixed parameter array. Set up a default (component params unfixed and background offset fixed) when the length is invalid.

**Checklist**

- [X] changelog updated / ~no changelog update needed~
- [x] ~e2e test passing~ / added corresponding fix
- [x] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [X] added reviewers and assignee
- [X] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Comment by YuHsuan-Hwang** [comment]
New changes (also updated in the description):
* Support background as a constant or a free fitting parameter.
* Check for length of the fixed parameter array. Set up a default when the length is invalid.

protobuf PR is required for sending the fitting result of the background as a free parameter.

**Comment by kswang1029** [comment]
feature-wise this looks good. Please proceed code review.

**Comment by kswang1029** [comment]
@YuHsuan-Hwang When a region is selected as the fitting area, the fitting log reports the area is entire image.

Screen Shot 2023-03-07 at 12 38 22

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 This is a frontend issue. I forgot to update this part ... . Please check the frontend fix, thanks.

**Review by kswang1029 — APPROVED** [review]
feature-wise this is looking very good. 👍 Please proceed code review.

**Review by veggiesaurus — APPROVED** [review]

**Review by confluence — APPROVED** [review]

**Pull request merged**
