### PR TITLE
Option to keep previous moment images

### PR DESCRIPTION
**Pull request by pford**
Keep previous moment images for an image (file_id) by creating a new name and file id from the source file_id and an index.

* What is implemented or fixed?
Adds feature in #1202 

* How does this PR solve the issue?
A `keep` field was added to MomentRequest.  This increments a moment index in Frame which is appended to the image names and used to create unique file ids for the generated images.

* Are there any companion PRs (frontend, protobuf)?
protobuf [#76](https://github.com/CARTAvis/carta-protobuf/pull/76).  frontend [#2059](https://github.com/CARTAvis/carta-frontend/pull/2059)

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Use the Moments dialog to generate images with "Keep previous Moments images" enabled (assuming it is like the PV dialog).

**Checklist**

- [x] changelog updated
- [x] ~e2e test passing~ / added corresponding fix
- [x] protobuf updated for new message field
- [x] added reviewers and assignee
- [x] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Comment by pford** [comment]
Ready to test when frontend development is complete.

**Comment by kswang1029** [comment]
@pford @crocka The keep function for moment images appears fine. I noticed that the keep function for pv images seems broken. Could you have a look?

**Comment by kswang1029** [comment]
@pford with the help from @crocka it might be that this branch is not updated with the current dev backend. Some test results
- `dev` frontend + `dev` backend: keep pv works
- `carli/2054_support_keeping_moment_image` + `dev` backend: keep pv works
- `carli/2054_support_keeping_moment_image` + `pam/1202_keep_moments`: keep pv does not work

**Comment by pford** [comment]
@kswang1029 I updated the backend and protobuf branches.  Please re-test.

**Review by kswang1029 — APPROVED** [review]
tested manually and automatically with e2e tests. All looking good, except UI changes which break moment generator tests. A branch has been created to address the changes.

**Review by markccchiang — APPROVED** [review]

**Review by confluence — APPROVED** [review]

**Pull request merged**
