### PR TITLE
Fix file info headers for dummy coordinate system (dev)

### LINKED ISSUE #436: Regression: Opening certain files results in invalid WCS
There's a regression since CARTA 1.2.2, where opening some HST images (e.g. this 1.6 GB file [here](https://archive.stsci.edu/missions/hlsp/candels/goods-n/gn-tot/v1.0/60mas-all/hlsp_candels_hst_acs_gn-tot-60mas_f606w_v1.0_drz.fits)) results in cassacore giving up the parsing of WCS information and instead just using dummy WCS. 

The output from the backend is shown below. The file loads fine with CARTA 1.2 an 1.2.2

```
2020-02-07 06:47:02	INFO	FITSCoordinateUtil::fromFITSHeader	celfix incurred the error Invalid parameter value
2020-02-07 06:47:02	INFO	FITSCoordinateUtil::fromFITSHeader	cylfix incurred the error Invalid parameter value
2020-02-07 06:47:02	WARN	FITSCoordinateUtil::fromFITSHeader	The wcs function failures are too severe to continue ...
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	No proper coordinate system defined in FITS file. Using dummy linear system instead.
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
```

### PR DESCRIPTION
**Pull request by pford**
Dummy linear coordinates are used when there is a wcslib error reading the headers. Fixed the extended file info header entries to use the original FITS headers rather than those returned by this coordinate system for the frontend to use with AST. Also fixed Region seg fault for image with no direction coordinate.

### CODE REVIEW

**Comment by pford** [comment]
Fixed merge conflict and @kswang1029 this worked for me with the pacs160_js.fits image.

**Comment by pford** [comment]
I added a HeaderEntry comment field in protobuf branch pam/header_entry_comment, and updated this branch to use it.  Must be merged with corresponding protobuf and frontend merges.

**Comment by veggiesaurus** [comment]
@pford what exactly needs to change with the frontend here? Adding an additional field to the protobuf message wouldn't break anything, and I don't think the frontend currently uses the comments, although we should display them, I guess. If you can fix the merge conflicts, I can put together a frontend branch that shows headers' comments as well

**Comment by pford** [comment]
I fixed the merge conflicts, don't know why the CentOS7 tests are failing.

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
