### PR TITLE
Fix extrema stat for whole-image regions of HDF5 files

### PR DESCRIPTION
**Pull request by confluence**
The stats widget uses the whole-image stats for HDF5 files.

### CODE REVIEW

**Comment by kswang1029** [comment]
@confluence @veggiesaurus I tested with the test hdf5 images on the mix server and it works. Sorry not spotting this in the previous PR🙈

**Comment by confluence** [comment]
This should now also fix #674.

**Review by kswang1029 — APPROVED** [review]
tested with sample HDF5 images on mix n match and it works. 

Just curious, for a single-pixel region, we see an empty plot with stat=stdDev with an HDF5 cube. With a fits cube, we see a "line" at y=0. Does this imply in the HDF5 case the backend does not supply an array with all elements 0? Note this difference does not have usability impact I think.

**Comment by confluence** [comment]
The formula we use for standard deviation involves division by `num_pixels - 1`, so if there's only one pixel we get NAN. I'm not sure if the difference in behaviour between FITS and HDF5 is a difference in the formula that casacore uses (I thought that we had matched these exactly) or an artifact of zero being used as a default value somewhere instead of NAN. I see that in the stats widget both files show the value as zero, so I suspect the latter.

**Comment by confluence** [comment]
After a discussion with @veggiesaurus I have removed the entire lazy min/max optimisation, and simplified the code.

**Review by veggiesaurus — APPROVED** [review]
@kswang1029 please re-test after the latest commits

**Comment by kswang1029** [comment]
@veggiesaurus ready for merge. 👍

**Pull request merged**
