### PR TITLE
Make default image 3D

### PR DESCRIPTION
**Pull request by confluence**
Generate a 3D default fits file from the original RGB image to work around [frontend issue #1418](https://github.com/CARTAvis/carta-frontend/issues/1418).

Casacore generates the correct default headers for a 3D image with minimal headers, but not for a 2D image with minimal headers.

Is 3.1M excessive for this image? I could export it at a lower resolution.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
can't you just make the 3rd axis degenerate?

**Comment by confluence** [comment]
Good point -- let me try that.

**Comment by confluence** [comment]
That works. I have updated the file.

**Comment by veggiesaurus** [comment]
that's fine, but we should probably fix https://github.com/CARTAvis/carta-frontend/issues/1418 anyway :) 

But this at least gives us breathing room in case the issue is a CASA one, rather than CARTA

**Pull request merged**
