### PR TITLE
Use mipmapped datasets and cached tile data from HDF5 files instead of the full image cache

### LINKED ISSUE #491: Add mip and range to spectral and spatial profile requests (backend)
I am currently integrating support for several new HDF5 schema features (mipmaps and chunked datasets) into the backend. These features allow us to use much less memory when loading large files. However, a drop in the performance of spatial profiles has become the major outstanding sticking point.

For HDF5 files which have these schema features, we no longer cache an entire full-resolution channel (unless we need to calculate contours) or downsample data on demand. Instead, we load precalculated downsampled data from mipmap datasets, or load tiles of full-resolution data as they are needed. Recent tiles are stored in an LRU cache so that they can be reused.

This works pretty well for rendering the image view. However, to calculate spatial profiles, we need a full row and column of tiles. For very large images, when the view is zoomed out all the way, small changes in cursor position translate to large distances in the image, which cross tile boundaries and thus require frequent reads of new tile data from the file. This adds a very large delay to the spatial profile widget which cannot easily be mitigated -- whether we abort calculations for old positions when the cursor moves, or allow some of them to be completed, we display data with a considerable lag, which is confusing and makes the widget feel very unresponsive.

I think that we could improve this by allowing the backend to send approximate profiles (which could be produced much more quickly, for example by being read from mipmaps) in addition to the slower, exact profiles. I understand that there are important differences between the exact profiles and their approximations, but I believe that displaying approximate profiles for the current cursor position, as a preview, would feel more responsive and intuitive than displaying exact profiles with a lag. The frontend could render approximate profiles slightly differently, for example with a paler line colour, to indicate that they are approximate. We could also perhaps delay saving data from the widget until we have received an exact profile.

A possibility is to add a `mip` field to the `SPATIAL_PROFILE_DATA` message. It would be up to the backend to send both approximate and exact profiles, or just exact ones, depending on the file format and the situation. Nothing would need to change for FITS and other formats.

### PR DESCRIPTION
**Pull request by confluence**
This implements the functionality described in #347. I have tested the branch with several local images, but it requires more extensive testing.

Closes #491 

Companion PR of https://github.com/CARTAvis/carta-frontend/pull/1310

### CODE REVIEW

**Comment by confluence** [comment]
Note: to access the new features, you need to use HDF5 images created with the latest converter (schema version 0.3). This is currently in a [branch](https://github.com/idia-astro/cpp_hdf5converter/tree/chunks-and-mipmaps), but I will follow up on the PR so that we can merge it into dev.

**Review by pford — APPROVED** [review]
Looks quite good to me.

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
please fix merge conflicts, so we can see if #447 fixes things

**Comment by confluence** [comment]
This PR implements #491. It needs to be built with the protocol buffer branch `confluence/spatial_profile_mip_and_range`. These branches introduce breaking changes to the interface, and should only be merged with the corresponding frontend changes.

**Comment by confluence** [comment]
Update: if no mipmaps are available and a mip >= 2 is requested, we now use min/max decimation to downsample the data. In future we could add min and max mipmaps to the HDF5 file schema.

Outstanding questions:

1. should the start and end fields in the returned profile reflect the actual endpoints that bound downsampled or decimated data? These may be different to the requested endpoints because of rounding.
2. The two downsampling methods may return different downsampled profile sizes, also because of rounding. Is this a problem?

**Comment by veggiesaurus** [comment]
@confluence can we add https://github.com/CARTAvis/carta-backend/issues/712 to this, while I sort out the last couple of frontend issues?

**Comment by confluence** [comment]
Yes, I think we can do that.

(Edit: I can go either way; maybe let's merge this in the meantime. Until we can disable generation of the mipmaps and rotated dataset, all HDF5 files have them anyway.)

**Comment by kswang1029** [comment]
With the frontend: origin/angus/mip_range_icd_change 91f1352 and the backend origin/confluence/hdf5-mipmaps 165db40 

Segfault. This is with a 10000x10000 FITS image. At a zoomed out scale and requesting spatial profiles, we firstly see the green cloud appears then the backend crashes.

https://user-images.githubusercontent.com/20819712/107332252-e6179d00-6aee-11eb-8c41-4d39347b8c1a.mp4

**Comment by kswang1029** [comment]
With the frontend: origin/angus/mip_range_icd_change 91f1352 and the backend origin/confluence/hdf5-mipmaps 165db40

not sure if i am seeing things here: when i load an image and try zoom/pan/request spatial profiles, then load another image, the backend crashes while the new image is loading. Cannot reproduce with dev.

**Comment by confluence** [comment]
@kswang1029 can you reproduce either of those crashes with the updated versions of this backend, frontend and protobuf branch? I haven't been able to.

I would like to modify the code to share the tile pool between all frames in a session, instead of having one per frame, but I'm not convinced that the current model could have caused the multiple image crash, and I'm not sure why the single FITS image would have crashed (unless the image cache wasn't loaded somewhere). I also created a 10kx10k noise image, but did not get a crash.

**Comment by kswang1029** [comment]
With backend `c7162762d1664713b20706ed2540b7ffb497c12a` (confluence/hdf5-mipmaps) and frontend `a152d31c8f33472dba7eb129fe7c333e5820cbb5` (angus/mip_range_icd_change), when I try to load a 10k x 10k FITS image, the image loads with empty spatial profile then the backend crashes. 

Am I using the right commits?

**Comment by confluence** [comment]
@kswang1029 are you also changing the protobuf commit / branch to `7ed3bf23e72f0b10705d643800d359f0e82decf3` / `confluence/spatial_profile_mip_and_range`?

Can you run the backend with debug verbosity and paste the output?

How did you make the FITS file? Can you please paste the headers? (The raw headers obtained with `fitsheader`, not the generated headers from the file browser.)

Are you loading the file off HDD or SSD?

**Comment by kswang1029** [comment]
> @kswang1029 are you also changing the protobuf commit / branch to `7ed3bf23e72f0b10705d643800d359f0e82decf3` / `confluence/spatial_profile_mip_and_range`?

Yes.

> 
> Can you run the backend with debug verbosity and paste the output?
> 

> octopus:build kswang$ ./carta_backend --no_http --port 3002 --omp_threads 16 --debug_no_auth --verbosity 5
[2021-04-27 15:24:04.342] [info] Writing to the log file: /Users/kswang/.carta/log/carta.log
[2021-04-27 15:24:04.342] [debug] Using command-line settings
[2021-04-27 15:24:04.342] [info] /Users/kswang/carta_build/carta-backend/build/./carta_backend: Version 2.0.0-dev.21.04.21
[2021-04-27 15:24:04.347] [info] Listening on port 3002 with top level folder /, starting folder /Users/kswang/carta_build/carta-backend/build, and 16 OpenMP worker threads
[2021-04-27 15:24:04.565] [debug] 0x7fdd5580b600 ::Session (1)
[2021-04-27 15:24:04.565] [info] Session 1 [127.0.0.1] Connected. Num sessions: 1
[2021-04-27 15:24:07.725] [debug] WebSocket closed with code 1001 and message ''.
[2021-04-27 15:24:07.725] [info] Client 1 [127.0.0.1] Deleted. Remaining sessions: 1
[2021-04-27 15:24:07.725] [debug] 0x7fdd5580b600 ~Session 0
[2021-04-27 15:24:07.725] [info] No remaining sessions.
[2021-04-27 15:24:50.422] [debug] 0x7fdd5702b000 ::Session (1)
[2021-04-27 15:24:50.422] [info] Session 2 [127.0.0.1] Connected. Num sessions: 1
2021-04-27 07:25:06	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
2021-04-27 07:25:06	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2021-04-27 07:25:06	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
2021-04-27 07:25:09	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
2021-04-27 07:25:09	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2021-04-27 07:25:09	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
[2021-04-27 15:25:09.206] [warning] Session 2: Image has no beam information.
[2021-04-27 15:25:09.364] [debug] The compression ratio for tile (layer:2, x:2, y:0) is 7.172.
[2021-04-27 15:25:09.364] [debug] The compression ratio for tile (layer:2, x:2, y:1) is 12.800.
[2021-04-27 15:25:09.387] [debug] The compression ratio for tile (layer:2, x:0, y:2) is 5.862.
[2021-04-27 15:25:09.387] [debug] The compression ratio for tile (layer:2, x:0, y:0) is 5.690.
[2021-04-27 15:25:09.387] [debug] The compression ratio for tile (layer:2, x:1, y:1) is 5.010.
[2021-04-27 15:25:09.387] [debug] The compression ratio for tile (layer:2, x:1, y:0) is 4.952.
[2021-04-27 15:25:09.388] [debug] The compression ratio for tile (layer:2, x:0, y:1) is 5.018.
[2021-04-27 15:25:09.388] [debug] The compression ratio for tile (layer:2, x:1, y:2) is 6.289.
[2021-04-27 15:25:09.389] [debug] Using high compression quality. Previous compression ratio: 40.787
[2021-04-27 15:25:09.389] [debug] The compression ratio for tile (layer:2, x:2, y:2) is 10.698.
Segmentation fault: 11
octopus:build kswang$ ./carta_backend --no_http --port 3002 --omp_threads 16 --debug_no_auth --verbosity 6
[2021-04-27 15:29:38.487] [info] Writing to the log file: /Users/kswang/.carta/log/carta.log
[2021-04-27 15:29:38.487] [info] /Users/kswang/carta_build/carta-backend/build/./carta_backend: Version 2.0.0-dev.21.04.21
[2021-04-27 15:29:38.494] [info] Listening on port 3002 with top level folder /, starting folder /Users/kswang/carta_build/carta-backend/build, and 16 OpenMP worker threads
[2021-04-27 15:32:30.586] [info] Session 1 [127.0.0.1] Connected. Num sessions: 1
2021-04-27 07:32:38	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
2021-04-27 07:32:38	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2021-04-27 07:32:38	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
2021-04-27 07:32:40	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
2021-04-27 07:32:40	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2021-04-27 07:32:40	WARN	FITSImage::getImageAttributes (file /Users/kswang/carta_build/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
[2021-04-27 15:32:40.047] [warning] Session 1: Image has no beam information.
Segmentation fault: 11


> How did you make the FITS file? Can you please paste the headers? (The raw headers obtained with `fitsheader`, not the generated headers from the file browser.)

Try this (an HST image): https://drive.google.com/file/d/1lfEGVKMc1GZhQ0BWhONL0654tArr81Re/view?usp=sharing

> 
> Are you loading the file off HDD or SSD?

SSD

**Comment by confluence** [comment]
I already have a file with that name (I'm re-downloading it to make 100% sure it's the exact same file) and I can't reproduce the crash with that file here. I will have a look at the debugging information you posted on Slack.

**Comment by confluence** [comment]
Thanks very much to @kswang1029 for helping to debug the crash which I couldn't reproduce -- it was an indexing error caused by rounding up past the bounds of the image dimensions.

This should now be working correctly, ~but I would like to make a minor optimisation to the way the pool of tile objects works~. The optimisation can wait until after 2.0!

**Comment by kswang1029** [comment]
> With the frontend: origin/angus/mip_range_icd_change 91f1352 and the backend origin/confluence/hdf5-mipmaps [165db40](https://github.com/CARTAvis/carta-backend/commit/165db4025561c6e7abfc0fb3ae9d6d25486f0ffd)
> 
> not sure if i am seeing things here: when i load an image and try zoom/pan/request spatial profiles, then load another image, the backend crashes while the new image is loading. Cannot reproduce with dev.

and cannot reproduce with backend 549c152510e8988f7fa038f6f0242403fa7969cc + frontend fb65497e33c5c4d39aeddea689f1fe0454ca8a6d 👍

**Comment by veggiesaurus** [comment]
image

@kswang1029 Minor addition: there's now a file info entry when mipmaps exist.

**Comment by kswang1029** [comment]
> image
> 
> @kswang1029 Minor addition: there's now a file info entry when mipmaps exist.

no "Has MipMaps = F" if there is no mip map data set?

**Comment by kswang1029** [comment]
> image
> 
> @kswang1029 Minor addition: there's now a file info entry when mipmaps exist.

A more general question: would it be necessary to show info for other pre-calculated data too (eg histogram)? (ie why mipmap is special here?) Or is this a temporary info until most of hdf5 images have mipmap data?

**Comment by veggiesaurus** [comment]
@kswang1029 the main reason is that not all HDF5 files have mipmaps. I didn't really want to add additional flags to everything else (FITS, etc), so I thought I'd just add the mipmap entry if its true. 

I guess we could also add "Has rotated dataset", since that's another thing that makes a major difference to UX? (and will probably make a big difference with PV)

**Comment by kswang1029** [comment]
> @kswang1029 the main reason is that not all HDF5 files have mipmaps. I didn't really want to add additional flags to everything else (FITS, etc), so I thought I'd just add the mipmap entry if its true.
> 
> I guess we could also add "Has rotated dataset", since that's another thing that makes a major difference to UX? (and will probably make a big difference with PV)


I see. OK. and moments :)

**Comment by confluence** [comment]
Now that this has been delayed to an intermediate release, I will:

- [x] expand the spatial profile unit tests from the basic test which was recently merged into dev, to cover all the different cases
- [ ] ~make the tile pool per-session rather than per-cache.~

Upon reflection, I think that a sensible implementation of a shared tile pool is complicated enough to be a separate feature, and it may not even be a necessary optimisation. I think that we should revisit this later separately.

**Comment by confluence** [comment]
@kswang1029 @veggiesaurus @pford this is ready to be re-tested. You will need to update the matching protobuf and frontend branches.

**Comment by kswang1029** [comment]
@confluence @veggiesaurus I tested this branch 4191b7b with the frontend branch Angus/mip_range_icd_change 81c1407 and see an issue with normal FITS file: animation playback does not work. The raster image is not updating. Could you confirm this is the case?

**Comment by confluence** [comment]
I have confirmed this with a 10x10x10 test image.

**Comment by veggiesaurus** [comment]
> @confluence @veggiesaurus I tested this branch [4191b7b](https://github.com/CARTAvis/carta-backend/commit/4191b7bc6ff814e618c6921de3878a4ba4ccb7af) with the frontend branch Angus/mip_range_icd_change 81c1407 and see an issue with normal FITS file: animation playback does not work. The raster image is not updating. Could you confirm this is the case?

@kswang1029 are the tiles being sent from the backend?

**Comment by confluence** [comment]
I think I found the problem -- please re-test. I should add a test for this.

**Comment by kswang1029** [comment]
@confluence confirmed with 98abfd0 that animation playback is functional for both FITS and HDF5 cubes.

**Review by kswang1029 — APPROVED** [review]
this backend part of the mip map feature works fine. 👍

**Comment by confluence** [comment]
@veggiesaurus please check exactly how the frontend is handling decimated data -- previously the data was not truncated correctly, so you would have been receiving the full-resolution data partially overwritten with the decimated data at the start. This is now fixed in the backend, so the data should be truncated to just the decimated length.

**Pull request merged**
