### PR TITLE
Use default axes for incomplete fits header

### LINKED ISSUE #596: Fits file doesn't load when header doesn't adhere to fits standard
Copy from @veggiesaurus:

There are a couple of problems with the FITS header.
(for ref: table 7 of the FITS standard: https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf)
1. Images need to have headers in the right order (NAXIS, then NAXIS1, ...NAXIS). This has (a) a gap between NAXIS values and (b) additional NAXIS headers (it has up to 4)
2. Then there also appears to be a CASA bug, where including additional CDELT, CRPIX, etc prevent the file from being read. Easiest thing to do is to trim the extra axis 3 and 4 headers, or pad them:
```
SIMPLE  =                    T                                                  
BITPIX  =                  -64                                                  
NAXIS   =                    4                                                  
NAXIS1  =                 9203                                                  
NAXIS2  =                 4706                                                  
NAXIS3  =                    1                                                  
NAXIS4  =                    1                                                  
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
CTYPE1  = 'RA---TAN'                                                            
CTYPE2  = 'DEC--TAN'                                                            
CTYPE3  = 'FREQ'                                                                
CTYPE4  = 'STOKES'                                                              
EQUINOX =                 2000                                                  
CRVAL1  =         35.152236620                                                  
CRVAL2  =         -4.833701903                                                  
CRVAL3  =          1.000000000                                                  
CRVAL4  = 1283895507.812500000                                                  
CRPIX1  =               4601.5                                                  
CRPIX2  =                2352.                                                  
CRPIX3  =          1.000000000                                                  
CRPIX4  =          1.000000000                                                  
CDELT1  =         -0.000305556                                                  
CDELT2  =          0.000305556                                                  
CDELT3  =          1.000000000                                                  
CDELT4  =          1.000000000                                                  
CROTA2  =        359.999992933
```
and
```
SIMPLE  =                    T                                                  
BITPIX  =                  -64                                                  
NAXIS   =                    2                                                  
NAXIS1  =                 9203                                                  
NAXIS2  =                 4706                                                  
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
CTYPE1  = 'RA---TAN'                                                            
CTYPE2  = 'DEC--TAN'                                                            
EQUINOX =                 2000                                                  
CRVAL1  =         35.152236620                                                  
CRVAL2  =         -4.833701903                                                  
CRPIX1  =               4601.5                                                  
CRPIX2  =                2352.                                                  
CDELT1  =         -0.000305556                                                  
CDELT2  =          0.000305556                                                  
CROTA2  =        359.999992933
```

both work
(1) is a FITS standard, (2) is a CASA bug. We could try submit a PR to casacore to fix (2), I think. But (1) is probably best adhered to

**Confirm:** Re-formatting the header as a work-around solves the issue.

### PR DESCRIPTION
**Pull request by pford**
Closes #596 .  For 4D image, assumes axes [x, y, spectral, stokes] when coord sys cannot determine spectral and stokes from headers.

### CODE REVIEW

**Review by veggiesaurus — APPROVED** [review]
this looks good to me. @kswang1029 please test

**Comment by kswang1029** [comment]
Could you provide a case that should be supported with this PR but not with v1.4? I created a test image such as 
Screen Shot 2021-01-19 at 1 19 46 PM
with the 3rd axis as "Sponge" and the 4th axis as "Bob" but it is already handled with v1.4 with the 3rd axis interpreted as "Channel" and the 4th axis interpreted as "Stokes" in the animator.

**Comment by pford** [comment]
The use case is there are some axis headers defined but others are missing, e.g. NAXIS3, CRVAL3, CRPIX3, CDELT3 are defined but no CTYPE3 or CUNIT3 exists in the headers for a 3D / 4D image.  The backend should assume axis 3 spectral, axis 4 stokes and load the image rather than sending an error message.

**Comment by kswang1029** [comment]
I generated a FITS image cube with 4-dimensions but with missing CTYPE3 and CTYPE4. It loads fine with v1.4 and the animator recognizes the third as channel and the forth as stokes. 🤔🤔🤔

Screen Shot 2021-01-21 at 11 19 27 AM

**Comment by kswang1029** [comment]
anyway, with 645eaac the above test FITS image without CTYPE3 and CTYPE4 is loaded successfully.

**Pull request merged**
