### PR TITLE
Refactor Session, Frame

### PR DESCRIPTION
**Pull request by pford**
Moved code from Session to Frame to prepare for ROI (issue #80). Region parameters validated and stored in Region class. Next step will be to create lattice region(s) in Region from these parameters, to use in Frame to create a SubLattice from the Lattice for the entire image.

All tests pass in this branch.  Also updated version number to 1.1.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
Just browsing through the code, surely there's nothing wrong with defining a region that has its center off the image, such as the first image below? Currently, your checks would pass with the region in the second image below, but fail with the region in the first image if I'm understanding the code correctly. 
image

image

Also not sure that we should prevent regions that have larger widths than the image itself (e.g. below). This is important if the user wants to see a spectral profile of the entire file. 
image

@kswang1029 thoughts?

**Comment by kswang1029** [comment]
Ultimately with WCS group, images within the same group may have different FOV. So we do need the flexibility to define regions anywhere on the celestial sphere with any size.

**Comment by pford** [comment]
Modified so that if the region is completely outside the image range (region xrange < 0 or > image xmax, or region yrange < 0 or > image ymax) the region is invalid and will not be processed.

**Comment by pford** [comment]
There may be further refinements when I am able to test regions.  This is just a start.

**Comment by veggiesaurus** [comment]
@pford after discussing with @kswang1029 in more detail, the consensus is that regions should only be considered invalid and be rejected by `SET_REGION` if they contain malformed or invalid configurations, such as
- negative width or height
- NaN values in any of the control points
- The incorrect number of control points for the required region type

Thus regions that are entirely outside of the image range should not be flagged as invalid

**Comment by veggiesaurus** [comment]
@confluence and/or @markccchiang can you review this?

**Comment by pford** [comment]
OK, will apply criteria to POINT region points as well (except width/height).  Does the channel min/max need to be in range?  Of course applying such a region to the Lattice will fail, so what does SET_REGION_ACK success=true mean exactly?

**Comment by veggiesaurus** [comment]
I'd say for 1.1, yes, the channels should be in range.

 `success = true` means the region was defined correctly and assigned a region ID, and further changes to the region requirements and control points can be made. Any actual analysis product for that region would be empty / full of NaNs, but that's ok. 

As a reference, here's a region defined in DS9 that's entirely off the image: 
image
The resulting statistics blurb looks like this: 

```
center=-79 76
image

reg	sum	error		area		surf_bri		surf_err
				(pix**2)		(sum/pix**2)		(sum/pix**2)
---	---	-----		--------		------------		------------
1	0	0		0		-nan		-nan

reg	sum	npix	mean	median	min	max	var	stddev	rms	
---	---	----	----	------	---	---	---	------	---	
1	0	0	0	0	1.7976931e+308	-1.7976931e+308	0	0	0	

```

I'd imagine we'd want something similar, (although with NaNs in place of obviously incorrect values)

**Pull request merged**
